<?php
namespace App\Services;

use App\Core\Database;
use PDO;

final class ExerciseProgressService
{
    public function build(int $exerciseId,int $limit=10): array
    {
        $db=Database::connection();$stmt=$db->prepare("SELECT ws.id session_id,ws.session_type,ws.performed_at,ws.body_weight_kg,we.id workout_exercise_id,es.id set_id,es.position,es.set_type,es.weight_kg,es.repetitions,es.rest_seconds,es.notes,es.is_personal_record,es.completed_at FROM workout_sessions ws JOIN workout_exercises we ON we.workout_session_id=ws.id LEFT JOIN exercise_sets es ON es.workout_exercise_id=we.id AND es.completed=1 WHERE we.exercise_id=? AND ws.status='completed' ORDER BY ws.performed_at,ws.id,es.position");$stmt->execute([$exerciseId]);$rows=$stmt->fetchAll();
        $sessions=[];foreach($rows as $row){$id=(int)$row['session_id'];if(!isset($sessions[$id]))$sessions[$id]=['id'=>$id,'session_type'=>$row['session_type'],'performed_at'=>$row['performed_at'],'body_weight_kg'=>$row['body_weight_kg'],'sets'=>[]];if($row['set_id'])$sessions[$id]['sets'][]=$row;}
        $sessions=array_values($sessions);$allWorking=[];$bestEver=null;$currentStreak=0;$longestStreak=0;$run=0;$previousBest=null;
        foreach($sessions as &$session){$working=array_values(array_filter($session['sets'],fn($set)=>$set['set_type']==='working'));$session['working']=$working;$session['warmup']=array_values(array_filter($session['sets'],fn($set)=>$set['set_type']==='warmup'));$session['ramp']=array_values(array_filter($session['sets'],fn($set)=>$set['set_type']==='ramp'));$session['best']=$this->best($working);$session['average_weight']=$working?array_sum(array_map(fn($set)=>(float)$set['weight_kg'],$working))/count($working):null;$session['total_reps']=array_sum(array_map(fn($set)=>(int)$set['repetitions'],$working));$session['best_reps']=$working?max(array_map(fn($set)=>(int)$set['repetitions'],$working)):null;$session['is_pr']=$session['best']&&(!$bestEver||$this->compare($session['best'],$bestEver)>0);if($session['is_pr'])$bestEver=$session['best'];$comparison=$previousBest&&$session['best']?$this->compare($session['best'],$previousBest):null;$session['comparison']=$comparison;$session['change']=$this->changeLabel($session['best'],$previousBest);if($comparison!==null&&$comparison>0){$run++;$longestStreak=max($longestStreak,$run);}elseif($comparison!==null)$run=0;$previousBest=$session['best']?:$previousBest;array_push($allWorking,...$working);}
        unset($session);$currentStreak=$run;$latest=$sessions?end($sessions):null;$previous=count($sessions)>1?$sessions[count($sessions)-2]:null;$record=$this->best($allWorking);$bestRepetitions=$allWorking?max(array_map(fn($set)=>(int)$set['repetitions'],$allWorking)):null;
        $target=$this->target($exerciseId);$recommendation=$this->recommendation($latest,$previous,$target);$stats=['sessions'=>count($sessions),'working_sets'=>count($allWorking),'average_weight'=>$allWorking?array_sum(array_map(fn($set)=>(float)$set['weight_kg'],$allWorking))/count($allWorking):null,'best_weight'=>$record?(float)$record['weight_kg']:null,'best_repetitions'=>$bestRepetitions,'average_repetitions'=>$allWorking?array_sum(array_map(fn($set)=>(int)$set['repetitions'],$allWorking))/count($allWorking):null,'total_repetitions'=>array_sum(array_map(fn($set)=>(int)$set['repetitions'],$allWorking)),'personal_records'=>count(array_filter($sessions,fn($session)=>$session['is_pr'])),'last_performed'=>$latest['performed_at']??null,'current_streak'=>$currentStreak,'longest_streak'=>$longestStreak];
        $chart=[];foreach($sessions as $session)$chart[]=['label'=>date('M j, Y',strtotime($session['performed_at'])),'best_weight'=>$session['best']?(float)$session['best']['weight_kg']:null,'best_repetitions'=>$session['best_reps'],'average_weight'=>$session['average_weight'],'best_set'=>$session['best']?((float)$session['best']['weight_kg'].' kg × '.(int)$session['best']['repetitions']):null];
        $timeline=[];foreach(array_slice(array_reverse($sessions),0,5) as $session)$timeline[]=['date'=>$session['performed_at'],'set'=>$session['best'],'type'=>$session['is_pr']?'record':(($session['comparison']??0)>0?'improved':(($session['comparison']??0)<0?'regressed':'same')),'label'=>$session['is_pr']?'New personal record':(($session['change']['label']??'First recorded performance'))];
        $insights=$this->insights($sessions,$target,$currentStreak,$recommendation);$achievements=$this->achievements($exerciseId,$stats,$record,$bestRepetitions,$sessions);
        $history=array_slice(array_reverse($sessions),0,max(5,min(50,$limit)));return compact('record','bestRepetitions','latest','previous','target','recommendation','stats','chart','timeline','insights','achievements','history')+['hasMore'=>count($sessions)>count($history)];
    }

    private function best(array $sets): ?array {if(!$sets)return null;usort($sets,fn($a,$b)=>$this->compare($b,$a));return $sets[0];}
    private function compare(?array $a,?array $b): int {if(!$a||!$b)return 0;$weight=(float)$a['weight_kg']<=>(float)$b['weight_kg'];return $weight?:((int)$a['repetitions']<=>(int)$b['repetitions']);}
    private function changeLabel(?array $latest,?array $previous): array {if(!$latest)return ['type'=>'none','label'=>'No working set'];if(!$previous)return ['type'=>'first','label'=>'First recorded performance'];$weight=(float)$latest['weight_kg']-(float)$previous['weight_kg'];$reps=(int)$latest['repetitions']-(int)$previous['repetitions'];if($weight>0)return ['type'=>'up','label'=>'+'.rtrim(rtrim(number_format($weight,2),'0'),'.').' kg'];if($weight<0)return ['type'=>'down','label'=>rtrim(rtrim(number_format($weight,2),'0'),'.').' kg'];if($reps>0)return ['type'=>'up','label'=>'+'.$reps.' repetition'.($reps===1?'':'s')];if($reps<0)return ['type'=>'down','label'=>$reps.' repetitions'];return ['type'=>'same','label'=>'Same performance'];}
    private function target(int $exerciseId): ?array {$stmt=Database::connection()->prepare("SELECT wte.set_count,wte.repetitions_min,wte.repetitions_max,wte.rest_seconds,e.weight_increment,wt.session_type FROM workout_template_exercises wte JOIN workout_templates wt ON wt.id=wte.workout_template_id AND wt.is_active=1 JOIN exercises e ON e.id=wte.exercise_id WHERE wte.exercise_id=? ORDER BY wt.id LIMIT 1");$stmt->execute([$exerciseId]);return $stmt->fetch()?:null;}
    private function recommendation(?array $latest,?array $previous,?array $target): array
    {
        if(!$latest||!$latest['working'])return ['type'=>'info','title'=>'Complete your first working sets','detail'=>'A recommendation will appear once a performance is recorded.'];if(!$target)return ['type'=>'info','title'=>'Keep building a baseline','detail'=>'This exercise has no programmed repetition target yet.'];$sets=$latest['working'];$minimum=(int)$target['repetitions_min'];$maximum=(int)$target['repetitions_max'];$planned=(int)$target['set_count'];$weight=(float)$latest['best']['weight_kg'];$increment=(float)$target['weight_increment'];$reps=array_map(fn($set)=>(int)$set['repetitions'],$sets);if(count($sets)>=$planned&&min($reps)>=$maximum)return ['type'=>'increase','title'=>'Increase the weight next session','detail'=>'You reached the top of the target range. Try '.rtrim(rtrim(number_format($weight+$increment,2),'0'),'.').' kg with clean technique.'];if(max($reps)<$minimum&&$previous&&max(array_map(fn($set)=>(int)$set['repetitions'],$previous['working']?:[['repetitions'=>$minimum]]))<$minimum)return ['type'=>'reduce','title'=>'Reduce by one increment','detail'=>'Two sessions are below the target range. Try '.max(0,$weight-$increment).' kg and rebuild your repetitions.'];if(min($reps)<$minimum)return ['type'=>'hold','title'=>'Keep the same weight','detail'=>'Stabilize every working set at '.$minimum.' repetitions before adding load.'];return ['type'=>'hold','title'=>'Add repetitions at the same weight','detail'=>'Stay at '.rtrim(rtrim(number_format($weight,2),'0'),'.').' kg until all '.$planned.' sets reach '.$maximum.' repetitions.'];
    }
    private function insights(array $sessions,?array $target,int $streak,array $recommendation): array {$items=[];if(count($sessions)<2)return ['Complete another session to unlock comparisons and progression insights.'];if($streak>=2)$items[]='You improved in '.$streak.' consecutive sessions.';$latest=end($sessions);if($target&&$latest['working']){$top=(int)$target['repetitions_max'];$near=count(array_filter($latest['working'],fn($set)=>(int)$set['repetitions']>=$top-1));if($near&&$near<count($latest['working']))$items[]='You are close to reaching the top of your target range.';if($near===count($latest['working']))$items[]='Your current target is fully reached.';}$recent=array_slice($sessions,-3);if(count($recent)===3&&count(array_unique(array_map(fn($s)=>$s['best']['weight_kg']??null,$recent)))===1)$items[]='Your working weight has stayed unchanged for three sessions.';if(strtotime($latest['performed_at'])<strtotime('-21 days'))$items[]='This exercise has not been trained for more than three weeks.';if(!$items)$items[]=$recommendation['detail'];return array_slice($items,0,3);}
    private function achievements(int $exerciseId,array $stats,?array $record,?int $bestReps,array $sessions): array {$db=Database::connection();(new AchievementCatalog())->sync();$stmt=$db->prepare("SELECT ad.*,au.unlocked_at FROM achievement_definitions ad LEFT JOIN achievement_unlocks au ON au.achievement_id=ad.id WHERE ad.exercise_id=? AND ad.is_active=1 ORDER BY ad.sort_order");$stmt->execute([$exerciseId]);$rows=$stmt->fetchAll();foreach($rows as &$row){$type=$row['evaluation_type'];$value=match($type){'exercise_count'=>(float)$stats['sessions'],'exercise_weight','weight_reps'=>(float)($record['weight_kg']??0),'exercise_reps'=>(float)($bestReps??0),'sets_top_range','sets_min_reps'=>(float)max(array_map(fn($s)=>count($s['working']),$sessions?:[['working'=>[]]])), 'consecutive_improvement'=>(float)$stats['current_streak'],default=>0};$row['current_value']=$value;$row['progress_percent']=min(100,(int)round($value/max(1,(float)($row['requirement_value']??1))*100));}unset($row);return $rows;}
}
