<?php
$title='Workout Mode';$workoutMode=true;$current=$state['current'];$session=$state['session'];$exerciseNumber=0;
foreach($state['exercises'] as $index=>$exercise)if((int)$exercise['id']===(int)$current['id'])$exerciseNumber=$index+1;
$targetSets=(int)$current['target_set_count'];$weight=$state['defaultWeight'];$reps=$state['currentSet']['repetitions']??'';$setType=$state['currentSet']['set_type']??'working';$quick=array_filter(array_map('intval',explode(',',$current['quick_repetition_values'])));$completedExercises=count(array_filter($state['exercises'],fn($exercise)=>$exercise['status']==='completed'));$progress=(int)round(($completedExercises+count($state['completedWorking'])/max(1,$targetSets))/max(1,count($state['exercises']))*100);
$setLabel=$setType==='warmup'?'WARM-UP SET':'WORKING SET '.(int)$state['workingSetNumber'].' OF '.$targetSets;
$dumbbellMode=$current['equipment']==='Dumbbells'?$current['effective_load_semantics']:null;$weightModeLabel=$dumbbellMode==='per_dumbbell'?'per dumbbell':($dumbbellMode==='total'?'total':null);
?>
<div class="mx-auto max-w-xl workout-mode-controls" data-workout-mode>
  <form id="workout-body-weight-form" class="mb-4 flex items-end gap-3 rounded-2xl border border-zinc-800 bg-zinc-900/70 p-3"><?= csrf_field() ?><div class="min-w-0 flex-1"><label for="workout-body-weight" class="text-xs font-semibold text-zinc-400">Today's body weight</label><div class="relative mt-1"><input id="workout-body-weight" name="weight_kg" type="number" min="20" max="400" step="0.1" value="<?= $session['body_weight_kg']!==null?e(number_format((float)$session['body_weight_kg'],1,'.','')):'' ?>" placeholder="e.g. 80.5" class="pr-10"><span class="pointer-events-none absolute right-3 top-3 text-sm text-zinc-500">kg</span></div></div><button class="btn-info min-h-11 px-4">Save</button><span id="body-weight-status" class="hidden text-xs text-emerald-400">Saved</span></form>
  <div class="mb-4"><div class="mb-2 flex justify-between text-xs text-zinc-500"><span>Exercise <?= $exerciseNumber ?> of <?= count($state['exercises']) ?></span><span><?= $progress ?>%</span></div><div class="h-2 overflow-hidden rounded-full bg-zinc-800"><div class="h-full rounded-full bg-emerald-500 transition-all" style="width:<?= $progress ?>%"></div></div></div>
  <div class="mb-4 flex items-start gap-2"><div class="min-w-0 flex-1 flex flex-wrap gap-2 text-xs"><?php foreach($state['exercises'] as $exercise):$selected=(int)$exercise['id']===(int)$current['id'];$unfinished=!in_array($exercise['status'],['completed','skipped'],true); ?><?php if($unfinished): ?><button type="button" data-switch-exercise="<?= (int)$exercise['id'] ?>" class="rounded-full px-2 py-1 <?= $selected?'bg-sky-700 font-bold text-white ring-1 ring-sky-400':($exercise['status']==='active'?'bg-sky-950 text-sky-300':'bg-zinc-900 text-zinc-500') ?>"><span><?= $exercise['status']==='active'?'●':'○' ?> <?= e($exercise['name']) ?></span><?php if((int)$exercise['rest_remaining']>0): ?><span class="ml-1 text-sky-300">⏱ <?= (int)$exercise['rest_remaining'] ?>s</span><?php endif; ?></button><?php else: ?><span class="rounded-full px-2 py-1 <?= $exercise['status']==='completed'?'bg-emerald-950 text-emerald-400':'bg-zinc-900 text-zinc-600' ?>"><?= $exercise['status']==='completed'?'✓':'—' ?> <?= e($exercise['name']) ?></span><?php endif; ?><?php endforeach; ?></div><?php if(count($state['remainingExercises'])>1): ?><button id="open-exercise-order" type="button" class="shrink-0 text-xs font-semibold text-violet-400">⇅ Order</button><?php endif; ?></div>
  <section class="rounded-3xl border border-zinc-800 bg-zinc-900 p-5 shadow-2xl sm:p-7">
    <p class="text-sm font-semibold <?= $setType==='warmup'?'text-orange-400':'text-emerald-400' ?>"><?= e($setLabel) ?></p><h1 class="mt-1 text-3xl font-black"><?= e($current['name']) ?></h1><p class="mt-1 text-zinc-400"><?= $targetSets ?> working sets · <?= (int)$current['target_repetitions_min'] ?>–<?= (int)$current['target_repetitions_max'] ?> reps<?php if($current['warmup_decision']==='added'): ?> · warm-up included<?php endif; ?></p>
    <?php if($state['previous']): ?><div class="mt-5 rounded-2xl bg-zinc-950/70 p-4"><p class="mb-2 text-xs font-semibold text-zinc-500">PREVIOUS WORKOUT</p><div class="flex flex-wrap gap-2"><?php foreach($state['previous'] as $set): ?><span class="rounded-lg bg-zinc-900 px-3 py-2 text-sm"><?= e($set['weight_kg']) ?> kg × <?= (int)$set['repetitions'] ?><?= $weightModeLabel?' · '.e($weightModeLabel):'' ?></span><?php endforeach; ?></div></div><?php endif; ?>
    <div class="mt-4 flex flex-wrap gap-4"><?php if($current['gif_path']||$current['image_path']||$current['instructions']): ?><button id="open-exercise-demo" type="button" class="text-sm font-semibold text-sky-400 hover:text-sky-300">▶ View demonstration</button><?php endif; ?><?php if($state['replacementCandidates']): ?><button id="open-exercise-replacement" type="button" class="text-sm font-semibold text-violet-400 hover:text-violet-300">⇄ Change exercise</button><?php endif; ?></div>
    <form id="active-set-form" class="mt-6 space-y-6"><?= csrf_field() ?><input id="drop-set-segments" type="hidden" name="segments">
      <div data-main-segment><div><p class="mb-2 text-center text-sm font-semibold text-zinc-400">Weight</p><div class="flex items-center justify-center gap-4"><button type="button" data-adjust-weight="-1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">−</button><div class="relative"><input id="workout-weight" name="weight_kg" inputmode="decimal" type="number" min="0" step="any" value="<?= $weight!==null?e(rtrim(rtrim(number_format((float)$weight,2,'.',''),'0'),'.')):'' ?>" class="w-36 border-0 bg-transparent p-0 text-center text-4xl font-black"><span class="block text-center text-sm text-zinc-500">kg<?= $weightModeLabel?' ('.e($weightModeLabel).')':'' ?></span></div><button type="button" data-adjust-weight="1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">+</button></div></div>
      <div class="mt-6"><p class="mb-2 text-center text-sm font-semibold text-zinc-400">Repetitions</p><div class="flex items-center justify-center gap-4"><button type="button" data-adjust-reps="-1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">−</button><input id="workout-reps" name="repetitions" inputmode="numeric" type="number" min="0" value="<?= e((string)$reps) ?>" placeholder="0" class="w-28 border-0 bg-transparent p-0 text-center text-5xl font-black"><button type="button" data-adjust-reps="1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">+</button></div><div class="mt-4 flex justify-center gap-2"><?php foreach($quick as $value): ?><button type="button" data-quick-reps="<?= $value ?>" class="rounded-xl bg-zinc-800 px-4 py-2 text-sm font-bold hover:bg-zinc-700"><?= $value ?></button><?php endforeach; ?></div></div></div>
      <?php if($setType==='working'): ?><div><button id="add-drop-segment" type="button" class="mx-auto block text-sm font-semibold text-orange-400">↘ Continue with lower weight</button><div id="drop-segment-list" class="mt-3 hidden space-y-3"></div></div><?php endif; ?>
      <details class="rounded-xl bg-zinc-950/60 p-3"><summary class="cursor-pointer text-sm text-zinc-400">Add a note</summary><div class="mt-3"><label>Optional note</label><input name="notes" placeholder="Add a short note"></div></details>
      <button id="complete-set" class="btn-primary w-full py-4 text-lg">✅ Complete set</button><p id="set-error" class="hidden text-center text-sm text-red-400"></p>
    </form>
    <?php if($setType==='working'): ?><details class="mt-4 border-t border-zinc-800 pt-4"><summary class="cursor-pointer text-center text-sm font-semibold text-zinc-400">More set options</summary><div class="mt-3"><button id="add-workout-set" type="button" class="btn-secondary w-full">＋ Add working set</button><p id="set-action-error" class="mt-2 hidden text-center text-sm text-red-400"></p><?php if($state['extraSets']): ?><div class="mt-3 space-y-2"><?php foreach($state['extraSets'] as $extra): ?><div class="flex items-center justify-between rounded-xl bg-zinc-950/60 px-3 py-2 text-sm"><span>Extra working set<?= (int)$extra['completed']===1?' · completed':'' ?><?= $extra['weight_kg']!==null?' · '.e(number_format((float)$extra['weight_kg'],2)).' kg':'' ?></span><?php if((int)$extra['completed']===0): ?><button type="button" data-remove-extra-set="<?= (int)$extra['id'] ?>" class="font-semibold text-red-400 hover:text-red-300">Remove</button><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></div></details><?php endif; ?>
  </section>
  <div class="mt-5 flex flex-wrap items-center justify-center gap-x-5 gap-y-3 text-sm"><button id="open-finish-early" type="button" class="font-semibold text-emerald-400 hover:text-emerald-300">Finish workout</button><form method="post" action="<?= e(route('workouts.active.cancel')) ?>" data-confirm="Cancel this workout? Every set entered in this workout will be permanently deleted." data-confirm-button="Cancel workout"><?= csrf_field() ?><button class="font-semibold text-red-400 hover:text-red-300">✕ Cancel workout</button></form></div>
</div>

<div id="finish-early-modal" class="fixed inset-0 z-[115] hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div class="w-full max-w-md rounded-3xl border border-zinc-700 bg-zinc-900 p-6 shadow-2xl"><p class="text-sm font-bold text-amber-400">FINISH WORKOUT</p><h2 class="mt-1 text-2xl font-black">Finish with exercises remaining?</h2><p class="mt-2 text-sm text-zinc-400">Your completed work stays saved. Untouched exercises will be marked as skipped.</p><div class="mt-4 rounded-2xl bg-zinc-950/60 p-4"><p class="mb-2 text-xs font-bold text-zinc-500">REMAINING</p><?php foreach($state['remainingExercises'] as $exercise): ?><p class="py-1 text-sm text-zinc-300">☐ <?= e($exercise['name']) ?></p><?php endforeach; ?></div><form method="post" action="<?= e(route('workouts.active.finish-early')) ?>" class="mt-5"><?= csrf_field() ?><button class="btn-primary w-full">Finish anyway</button></form><button id="continue-current-workout" type="button" class="btn-secondary mt-3 w-full">Continue workout</button><button id="cancel-finish-early" type="button" class="mt-3 w-full py-2 text-sm text-zinc-500 hover:text-white">Cancel</button></div></div>

<?php if($state['warmupPrompt']): ?><div id="warmup-modal" class="fixed inset-0 z-[120] flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div class="w-full max-w-sm rounded-3xl border border-zinc-700 bg-zinc-900 p-6 text-center shadow-2xl"><span class="text-4xl">🔥</span><h2 class="mt-3 text-xl font-black">Warm up for <?= e($current['name']) ?>?</h2><p class="mt-2 text-sm text-zinc-400">Would you like to perform a warm-up set?</p><div class="mt-6 grid grid-cols-2 gap-3"><button type="button" data-warmup-choice="no" class="btn-secondary">No</button><button type="button" data-warmup-choice="yes" class="btn-primary">Yes</button></div><p id="warmup-error" class="mt-3 hidden text-sm text-red-400"></p></div></div><?php endif; ?>
<div id="workout-overlay" class="fixed inset-0 z-50 hidden items-center justify-center bg-zinc-950/90 p-4 backdrop-blur"><div class="w-full max-w-sm rounded-3xl border border-zinc-700 bg-zinc-900 p-6 text-center shadow-2xl"><div id="overlay-rest"><p class="text-sm font-semibold text-sky-400">⏱️ REST · <?= e($current['name']) ?></p><p id="rest-countdown" class="my-4 text-6xl font-black tabular-nums">00:00</p><p class="text-zinc-400">Next set is ready when you are.</p><div class="mt-6 grid grid-cols-3 gap-2"><button data-timer="skip" class="btn-secondary min-h-0 px-2">Skip</button><button data-timer="add" class="btn-info min-h-0 px-2">+30 sec</button><button data-timer="pause" class="btn-secondary min-h-0 px-2">Pause</button></div><button id="enable-timer-alerts" type="button" class="mt-3 hidden w-full rounded-xl bg-violet-950/60 px-3 py-2 text-sm font-semibold text-violet-300 hover:bg-violet-900/60">🔔 Enable timer alerts</button><p id="timer-alert-status" class="mt-2 hidden text-xs text-zinc-500"></p><?php if(count($state['remainingExercises'])>1): ?><div class="mt-5 border-t border-zinc-800 pt-4"><p class="mb-2 text-xs font-bold text-zinc-500">TRAIN ANOTHER EXERCISE</p><div class="grid gap-2"><?php foreach($state['remainingExercises'] as $exercise):if((int)$exercise['id']===(int)$current['id'])continue; ?><button type="button" data-switch-exercise="<?= (int)$exercise['id'] ?>" class="rounded-xl bg-zinc-800 px-3 py-2 text-sm font-semibold text-sky-300 hover:bg-zinc-700"><?= e($exercise['name']) ?><?php if((int)$exercise['rest_remaining']>0): ?> · <?= (int)$exercise['rest_remaining'] ?>s<?php endif; ?></button><?php endforeach; ?></div></div><?php endif; ?></div><div id="overlay-complete" class="hidden"><p id="complete-icon" class="text-5xl">✅</p><h2 id="complete-title" class="mt-3 text-2xl font-black"></h2><p id="complete-detail" class="mt-2 text-zinc-400"></p><button id="continue-workout" class="btn-primary mt-6 w-full">Continue</button></div></div></div>

<?php if(count($state['remainingExercises'])>1): ?><div id="exercise-order-modal" class="fixed inset-0 z-[108] hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div class="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-3xl border border-zinc-700 bg-zinc-900 p-5 shadow-2xl"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold text-violet-400">EXERCISE ORDER</p><h2 class="text-xl font-black">Train in the order that works now</h2><p class="mt-1 text-sm text-zinc-500">Drag the remaining exercises or activate another one in parallel.</p></div><button id="close-exercise-order" type="button" class="flex h-10 w-10 items-center justify-center rounded-full bg-zinc-800 text-xl">×</button></div><div id="exercise-order-list" class="mt-4 space-y-2"><?php foreach($state['remainingExercises'] as $exercise):$selected=(int)$exercise['id']===(int)$current['id']; ?><div draggable="true" data-order-id="<?= (int)$exercise['id'] ?>" class="flex cursor-move items-center gap-3 rounded-2xl border border-zinc-800 bg-zinc-950/60 p-3"><span class="text-zinc-600">☰</span><strong class="min-w-0 flex-1 truncate"><?= e($exercise['name']) ?></strong><?php if($selected): ?><span class="text-xs font-semibold text-sky-400">Current</span><?php else: ?><button type="button" data-activate-exercise="<?= (int)$exercise['id'] ?>" class="text-xs font-semibold text-emerald-400"><?= $exercise['status']==='active'?'Switch':'Activate' ?></button><?php endif; ?></div><?php endforeach; ?></div><button id="save-exercise-order" type="button" class="btn-primary mt-4 w-full">Save order</button><p id="exercise-order-error" class="mt-3 hidden text-sm text-red-400"></p></div></div><?php endif; ?>

<?php if($current['gif_path']||$current['image_path']||$current['instructions']): ?><div id="exercise-demo-modal" class="fixed inset-0 z-[105] hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div class="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-3xl border border-zinc-700 bg-zinc-900 p-5 shadow-2xl"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold text-sky-400">DEMONSTRATION</p><h2 class="text-xl font-black"><?= e($current['name']) ?></h2></div><button id="close-exercise-demo" type="button" class="flex h-10 w-10 items-center justify-center rounded-full bg-zinc-800 text-xl">×</button></div><div class="mt-4 aspect-square overflow-hidden rounded-2xl bg-zinc-950"><img id="exercise-demo-media" data-gif="<?= e($current['gif_path']??'') ?>" data-image="<?= e($current['image_path']??'') ?>" alt="Demonstration of <?= e($current['name']) ?>" width="180" height="180" class="h-full w-full object-cover"></div><div id="exercise-demo-steps" class="mt-4 space-y-2 text-sm leading-relaxed text-zinc-300"></div><?php if($current['media_attribution']): ?><p class="mt-4 border-t border-zinc-800 pt-3 text-xs text-zinc-600"><?= e($current['media_attribution']) ?></p><?php endif; ?></div></div><?php endif; ?>
<?php if($state['replacementCandidates']): ?><div id="exercise-replacement-modal" class="fixed inset-0 z-[106] hidden items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl border border-zinc-700 bg-zinc-900 p-5 shadow-2xl"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold text-violet-400">CHANGE EXERCISE</p><h2 class="text-xl font-black"><?= e($current['muscle_group']) ?> alternatives</h2><p class="mt-1 text-sm text-zinc-500">Only this workout will be changed.</p></div><button id="close-exercise-replacement" type="button" class="flex h-10 w-10 items-center justify-center rounded-full bg-zinc-800 text-xl">×</button></div><div class="mt-4 grid gap-2 sm:grid-cols-2"><?php foreach($state['replacementCandidates'] as $candidate): ?><button type="button" data-replacement-exercise="<?= (int)$candidate['id'] ?>" class="flex min-h-20 items-center gap-3 rounded-2xl border border-zinc-800 bg-zinc-950/60 p-3 text-left transition hover:border-violet-700 hover:bg-violet-950/20"><?php if($candidate['image_path']): ?><img src="<?= e($candidate['image_path']) ?>" alt="" width="56" height="56" loading="lazy" class="h-14 w-14 shrink-0 rounded-xl object-cover"><?php else: ?><span class="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-zinc-800">💪</span><?php endif; ?><span class="min-w-0"><strong class="block truncate"><?= e($candidate['name']) ?></strong><small class="text-zinc-500"><?= e($candidate['equipment']??'No equipment') ?> · <?= (int)$candidate['recommended_rest_seconds'] ?> sec</small></span></button><?php endforeach; ?></div><p id="exercise-replacement-error" class="mt-3 hidden text-sm text-red-400"></p></div></div><?php endif; ?>
<script>window.workoutDemo=<?= json_encode(['steps'=>json_decode((string)($current['instruction_steps']??'[]'),true)?:[],'instructions'=>$current['instructions']??''],JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP) ?>;window.workoutMode={remaining:<?= (int)$state['remaining'] ?>,paused:<?= (int)($current['rest_paused_seconds']??0) ?>,exercise:<?= json_encode($current['name'],JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP) ?>,weightMode:<?= json_encode($weightModeLabel,JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP) ?>,increment:<?= (float)$current['weight_increment'] ?>,sound:<?= ($state['settings']['timer_sound_enabled']??'1')==='1'?'true':'false' ?>,vibration:<?= ($state['settings']['timer_vibration_enabled']??'1')==='1'?'true':'false' ?>};</script><script defer src="<?= e(asset('assets/js/workout-mode.js')) ?>"></script>
