<?php
$title='Workout Mode';$workoutMode=true;$current=$state['current'];$session=$state['session'];$exerciseNumber=0;foreach($state['exercises'] as $index=>$exercise)if((int)$exercise['id']===(int)$current['id'])$exerciseNumber=$index+1;
$setNumber=(int)$session['current_set_position'];$targetSets=(int)$current['target_set_count'];$weight=(float)($state['defaultWeight']??0);$reps=(int)($current['target_repetitions_min']??8);$quick=array_filter(array_map('intval',explode(',',$current['quick_repetition_values'])));$progress=(int)round((($exerciseNumber-1)+(($setNumber-1)/max(1,$targetSets)))/max(1,count($state['exercises']))*100);
?>
<div class="mx-auto max-w-xl">
  <div class="mb-4"><div class="mb-2 flex justify-between text-xs text-zinc-500"><span>Exercise <?= $exerciseNumber ?> of <?= count($state['exercises']) ?></span><span><?= $progress ?>%</span></div><div class="h-2 overflow-hidden rounded-full bg-zinc-800"><div class="h-full rounded-full bg-emerald-500 transition-all" style="width:<?= $progress ?>%"></div></div></div>
  <div class="mb-4 flex flex-wrap gap-2 text-xs"><?php foreach($state['exercises'] as $exercise): ?><span class="rounded-full px-2 py-1 <?= $exercise['status']==='completed'?'bg-emerald-950 text-emerald-400':($exercise['status']==='active'?'bg-sky-950 text-sky-300':'bg-zinc-900 text-zinc-500') ?>"><?= $exercise['status']==='completed'?'✓':($exercise['status']==='active'?'●':'○') ?> <?= e($exercise['name']) ?></span><?php endforeach; ?></div>
  <section class="rounded-3xl border border-zinc-800 bg-zinc-900 p-5 shadow-2xl sm:p-7">
    <p class="text-sm font-semibold text-emerald-400">SET <?= $setNumber ?> OF <?= $targetSets ?></p><h1 class="mt-1 text-3xl font-black"><?= e($current['name']) ?></h1><p class="mt-1 text-zinc-400">Target: <?= $targetSets ?> sets × <?= (int)$current['target_repetitions_min'] ?>–<?= (int)$current['target_repetitions_max'] ?> reps</p>
    <?php if($state['previous']): ?><div class="mt-5 rounded-2xl bg-zinc-950/70 p-4"><p class="mb-2 text-xs font-semibold text-zinc-500">PREVIOUS WORKOUT</p><div class="flex flex-wrap gap-2"><?php foreach($state['previous'] as $set): ?><span class="rounded-lg bg-zinc-900 px-3 py-2 text-sm"><?= e($set['weight_kg']) ?> kg × <?= (int)$set['repetitions'] ?></span><?php endforeach; ?></div></div><?php endif; ?>
    <form id="active-set-form" class="mt-6 space-y-6"><?= csrf_field() ?>
      <div><p class="mb-2 text-center text-sm font-semibold text-zinc-400">Weight</p><div class="flex items-center justify-center gap-4"><button type="button" data-adjust-weight="-1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">−</button><div class="relative"><input id="workout-weight" name="weight_kg" type="number" min="0" step="<?= e($current['weight_increment']) ?>" value="<?= e(number_format($weight,2,'.','')) ?>" class="w-36 border-0 bg-transparent p-0 text-center text-4xl font-black"><span class="block text-center text-sm text-zinc-500">kg</span></div><button type="button" data-adjust-weight="1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">+</button></div></div>
      <div><p class="mb-2 text-center text-sm font-semibold text-zinc-400">Repetitions</p><div class="flex items-center justify-center gap-4"><button type="button" data-adjust-reps="-1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">−</button><input id="workout-reps" name="repetitions" inputmode="numeric" type="number" min="0" value="<?= $reps ?>" class="w-28 border-0 bg-transparent p-0 text-center text-5xl font-black"><button type="button" data-adjust-reps="1" class="h-12 w-12 rounded-full bg-zinc-800 text-2xl hover:bg-zinc-700">+</button></div><div class="mt-4 flex justify-center gap-2"><?php foreach($quick as $value): ?><button type="button" data-quick-reps="<?= $value ?>" class="rounded-xl bg-zinc-800 px-4 py-2 text-sm font-bold hover:bg-zinc-700"><?= $value ?></button><?php endforeach; ?></div></div>
      <details class="rounded-xl bg-zinc-950/60 p-3"><summary class="cursor-pointer text-sm text-zinc-400">Add note or change set type</summary><div class="mt-3 grid gap-3 sm:grid-cols-2"><div><label>Set type</label><select name="set_type"><option value="working">Working</option><option value="warmup">Warm-up</option><option value="ramp">Ramp-up</option></select></div><div><label>Optional note</label><input name="notes" placeholder="Add a short note"></div></div></details>
      <button id="complete-set" class="btn-primary w-full py-4 text-lg">✅ Complete set</button><p id="set-error" class="hidden text-center text-sm text-red-400"></p>
    </form>
  </section>
  <div class="mt-5 flex flex-wrap items-center justify-center gap-x-5 gap-y-3 text-sm">
    <form method="post" action="<?= e(route('workouts.active.end')) ?>" data-confirm="End this workout? Completed sets will remain available as an abandoned workout." data-confirm-button="End workout"><?= csrf_field() ?><button class="text-zinc-400 hover:text-white">End workout</button></form>
    <form method="post" action="<?= e(route('workouts.active.cancel')) ?>" data-confirm="Cancel this workout? Every set entered in this workout will be permanently deleted." data-confirm-button="Cancel workout"><?= csrf_field() ?><button class="font-semibold text-red-400 hover:text-red-300">✕ Cancel workout</button></form>
  </div>
</div>

<div id="workout-overlay" class="fixed inset-0 z-50 hidden items-center justify-center bg-zinc-950/90 p-4 backdrop-blur"><div class="w-full max-w-sm rounded-3xl border border-zinc-700 bg-zinc-900 p-6 text-center shadow-2xl"><div id="overlay-rest"><p class="text-sm font-semibold text-sky-400">⏱️ REST</p><p id="rest-countdown" class="my-4 text-6xl font-black tabular-nums">00:00</p><p class="text-zinc-400">Next: <?= e($current['name']) ?> · Set <?= min($setNumber+1,$targetSets) ?> of <?= $targetSets ?></p><div class="mt-6 grid grid-cols-3 gap-2"><button data-timer="skip" class="btn-secondary min-h-0 px-2">Skip</button><button data-timer="add" class="btn-info min-h-0 px-2">+30 sec</button><button data-timer="pause" class="btn-secondary min-h-0 px-2">Pause</button></div></div><div id="overlay-complete" class="hidden"><p id="complete-icon" class="text-5xl">✅</p><h2 id="complete-title" class="mt-3 text-2xl font-black"></h2><p id="complete-detail" class="mt-2 text-zinc-400"></p><button id="continue-workout" class="btn-primary mt-6 w-full">Continue</button></div></div></div>
<script>window.workoutMode={remaining:<?= (int)$state['remaining'] ?>,paused:<?= (int)($session['rest_paused_seconds']??0) ?>,increment:<?= (float)$current['weight_increment'] ?>,sound:<?= ($state['settings']['timer_sound_enabled']??'1')==='1'?'true':'false' ?>,vibration:<?= ($state['settings']['timer_vibration_enabled']??'1')==='1'?'true':'false' ?>};</script><script defer src="/assets/js/workout-mode.js"></script>
