<?php $editing=isset($session);$title=$editing?'Edit workout':'New workout'; ?>
<h1 class="mb-6 text-3xl font-black"><?= e($title) ?></h1>
<form method="post" action="<?= e($editing?route('workouts.update',['id'=>$session['id']]):route('workouts.store')) ?>" id="workout-form" class="space-y-6" data-initial='<?= e(json_encode($session['exercises']??$preset,JSON_UNESCAPED_UNICODE)) ?>'><?= csrf_field() ?>
  <?php if(!$editing): ?><section class="card"><label for="workout_template">Workout plan</label><select id="workout_template"><option value="">Free workout</option><?php foreach($templates as $template): ?><option value="<?= (int)$template['id'] ?>" <?= (int)($selectedTemplate['id']??0)===(int)$template['id']?'selected':'' ?>><?= e($template['name']) ?> — <?= e(str_replace(['1','2','3','4','5','6','7'],['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],$template['scheduled_days'])) ?></option><?php endforeach; ?></select><p class="mt-2 text-sm text-zinc-400">Today's plan is selected automatically. You can choose another one.</p></section><?php endif; ?>
  <section class="card grid gap-4 sm:grid-cols-2"><div><label for="performed_at">Date and time</label><input id="performed_at" type="datetime-local" name="performed_at" required value="<?= e($editing?date('Y-m-d\TH:i',strtotime($session['performed_at'])):old('performed_at',$formDate.'T'.date('H:i'))) ?>"></div><div><label for="session_type">Workout type</label><input id="session_type" name="session_type" required placeholder="e.g. Legs" value="<?= e($session['session_type']??$selectedTemplate['session_type']??old('session_type')) ?>"></div><div><label for="body_weight_kg">Body weight (kg)</label><input id="body_weight_kg" type="number" step="0.01" min="0" name="body_weight_kg" value="<?= e($session['body_weight_kg']??old('body_weight_kg')) ?>"></div><div><label for="notes">Notes</label><textarea id="notes" name="notes" rows="2"><?= e($session['notes']??old('notes')) ?></textarea></div></section>
  <div id="exercise-list" class="space-y-4"></div>
  <template id="exercise-template"><section class="card exercise-block"><div class="mb-2 flex gap-2"><select data-name="exercise_id" required><option value="">Choose an exercise</option><?php foreach($exercises as $exercise): ?><option value="<?= (int)$exercise['id'] ?>" data-rest="<?= (int)$exercise['recommended_rest_seconds'] ?>"><?= e($exercise['muscle_group'].' · '.$exercise['name']) ?></option><?php endforeach; ?></select><button class="btn-secondary remove-exercise" type="button">×</button></div><p class="exercise-target mb-4 hidden text-sm font-semibold text-emerald-500"></p><div class="sets space-y-2"></div><button type="button" class="add-set mt-3 text-sm font-semibold text-emerald-500">+ Add set</button></section></template>
  <template id="set-template"><div class="set-row grid grid-cols-2 gap-2 rounded-xl bg-zinc-950 p-3 sm:grid-cols-6"><div><label>Type</label><select data-set-name="set_type"><option value="warmup">Warm-up</option><option value="ramp">Ramp-up</option><option value="working" selected>Working</option></select></div><div><label>Weight kg</label><input data-set-name="weight_kg" type="number" min="0" step="0.01"></div><div><label>Reps</label><input data-set-name="repetitions" type="number" min="0"></div><div><label>Rest sec</label><input data-set-name="rest_seconds" type="number" min="0"></div><div><label>Note</label><input data-set-name="notes"></div><div class="flex items-end gap-1"><button type="button" class="start-timer rounded-lg bg-emerald-950 px-3 py-2 text-emerald-300">Timer</button><button type="button" class="remove-set rounded-lg p-2 text-red-400">×</button></div></div></template>
  <button type="button" id="add-exercise" class="btn-secondary w-full">+ Add exercise</button><button class="btn-primary w-full" type="submit"><?= $editing?'Save changes':'Save workout' ?></button>
</form>
<div id="rest-timer" class="fixed bottom-6 right-4 z-50 hidden rounded-2xl border border-emerald-800 bg-zinc-900 p-4 shadow-2xl"><p class="text-xs uppercase text-emerald-500">Rest timer</p><p id="timer-value" class="text-3xl font-black tabular-nums">00:00</p><button id="stop-timer" class="mt-1 text-sm text-zinc-400">Stop</button></div>
