<?php
$title='Dashboard';$hour=(int)date('G');$greeting=$hour<12?'Good morning':($hour<18?'Good afternoon':'Good evening');$lastWorkout=$sessions[0]??null;
$heatmapCalendar=$stats['heatmapCalendar'];$trendColor=function($trend)use($stats){if($trend===null||in_array($stats['weightGoal'],['unset','maintain'],true))return 'text-zinc-500';$positive=$stats['weightGoal']==='gain'?$trend>0:$trend<0;return $positive?'text-emerald-400':'text-red-400';};
?>
<div id="body-weight-modal" class="fixed inset-0 z-[100] hidden items-center justify-center bg-black/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><form method="post" action="<?= e(route('body-weight.store')) ?>" class="w-full max-w-md rounded-3xl border border-zinc-700 bg-zinc-900 p-6 shadow-2xl"><?= csrf_field() ?><h2 class="text-xl font-black">⚖️ Record body weight</h2><p class="mt-1 text-sm text-zinc-400">One entry per day. Saving again updates today's value.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><div><label for="dashboard-weight-date">Date</label><input id="dashboard-weight-date" name="recorded_on" type="date" value="<?= e(date('Y-m-d')) ?>" required></div><div><label for="dashboard-weight">Weight (kg)</label><input id="dashboard-weight" name="weight_kg" type="number" min="20" max="400" step="0.1" value="<?= $stats['currentWeight']!==null?e(number_format($stats['currentWeight'],1,'.','')):'' ?>" required></div></div><div class="mt-6 grid grid-cols-2 gap-3"><button type="button" data-close-weight-modal class="btn-secondary">Cancel</button><button class="btn-primary">Save weight</button></div></form></div>
<section class="mb-5 grid grid-cols-2 gap-3 rounded-2xl border border-zinc-800 bg-gradient-to-r from-zinc-900 to-zinc-900/60 p-4 lg:grid-cols-4">
  <div><p class="text-xs text-zinc-500">💪 Today's workout</p><p class="font-bold"><?= e($activeWorkout['session']['session_type']??$stats['todayCompleted']['session_type']??$stats['todayWorkout']['session_type']??'Recovery day') ?></p></div>
  <div><p class="text-xs text-zinc-500">🏋️ Last workout</p><p class="font-bold"><?= e($lastWorkout['session_type']??'None yet') ?></p></div>
  <div><p class="text-xs text-zinc-500">⚖️ Current weight</p><p class="font-bold"><?= $stats['currentWeight']!==null?e(number_format($stats['currentWeight'],1)).' kg':'—' ?></p></div>
  <div><p class="text-xs text-zinc-500">📏 Measurements</p><p class="font-bold <?= $stats['due']?'text-amber-400':'text-emerald-400' ?>"><?= $stats['due']?'Due':'Completed' ?></p></div>
</section>

<div class="mb-5"><p class="text-sm font-semibold text-emerald-400"><?= e($greeting) ?> 👋</p><h1 class="text-3xl font-black"><?= e($dailyMessage) ?></h1><p class="mt-1 text-zinc-400">Your plan is ready when you are.</p></div>

<section data-dashboard-workout-card class="mb-5 overflow-hidden rounded-2xl border border-emerald-800/60 bg-gradient-to-br from-emerald-950/70 via-zinc-900 to-sky-950/40 p-5 text-center shadow-xl shadow-emerald-950/10 lg:text-left">
  <div class="grid gap-5 lg:grid-cols-[1fr_auto]"><div><p class="text-sm font-semibold text-emerald-400"><?= $activeWorkout?'● WORKOUT IN PROGRESS':($stats['todayCompleted']?'✅ WORKOUT COMPLETE':'💪 TODAY\'S WORKOUT') ?></p><h2 class="mt-1 text-2xl font-black"><?= e($activeWorkout['session']['session_type']??$stats['todayCompleted']['session_type']??$stats['todayWorkout']['session_type']??'Recovery day') ?></h2>
  <?php $dashboardExercises=$activeWorkout['exercises']??$stats['todayWorkout']['exercises']??[];if($dashboardExercises): ?><div class="mt-4 grid gap-2 sm:grid-cols-2"><?php foreach($dashboardExercises as $exercise):$status=$activeWorkout?$exercise['status']:($stats['todayCompleted']?'completed':'pending');?><p class="flex items-center justify-center gap-2 text-sm lg:justify-start <?= $status==='completed'?'text-emerald-400':'text-zinc-300' ?>"><span><?= $status==='completed'?'✓':($status==='active'?'●':'○') ?></span><?= e($exercise['name']??$exercise['exercise_name']) ?></p><?php endforeach; ?></div><?php else: ?><p class="mt-2 text-zinc-400">Rest, recover, and get ready for tomorrow.</p><?php endif; ?></div>
  <div class="flex items-end"><?php if($activeWorkout): ?><a class="btn-reminder w-full whitespace-nowrap" href="/workouts/active">▶ Resume workout</a><?php elseif($stats['todayCompleted']): ?><a class="btn-secondary w-full whitespace-nowrap" href="/workouts/<?= (int)$stats['todayCompleted']['id'] ?>">✅ View workout</a><?php elseif($stats['todayWorkout']): ?><form method="post" action="/workouts/start" class="w-full"><?= csrf_field() ?><input type="hidden" name="template_id" value="<?= (int)$stats['todayWorkout']['id'] ?>"><button class="btn-primary w-full whitespace-nowrap">🏋️ Start workout</button></form><?php else: ?><a class="btn-info w-full whitespace-nowrap" href="/workouts/custom/new">➕ Free workout</a><?php endif; ?></div></div>
</section>

<section data-measurement-reminder class="mb-5 flex flex-col items-center justify-center gap-3 rounded-xl border text-center sm:flex-row sm:justify-between sm:text-left <?= $stats['due']?'border-amber-700/60 bg-amber-950/20':'border-zinc-800 bg-zinc-900/40' ?> px-4 py-3"><div><p class="font-bold"><?= $stats['due']?'📏 Monthly measurements':'✅ Monthly measurements' ?></p><p class="text-xs text-zinc-500">Last: <?= $stats['lastMeasurement']?e(date('M j, Y',strtotime($stats['lastMeasurement']))):'No measurement yet' ?> · Next: <?= e(date('M j, Y',strtotime($stats['nextReminder']))) ?></p></div><a href="/measurements" class="<?= $stats['due']?'btn-reminder':'btn-secondary' ?> min-h-0 px-3 py-2 text-sm"><?= $stats['due']?'📏 Record measurements':'View measurements' ?></a></section>

<section class="mb-5 flex items-center justify-between gap-3 rounded-xl border border-sky-900/60 bg-sky-950/20 px-4 py-3"><div><p class="font-bold">⚖️ Current body weight</p><p class="text-sm <?= $stats['todayWeight']!==null?'text-zinc-300':'text-zinc-400' ?>"><?= $stats['todayWeight']!==null?e(number_format($stats['todayWeight'],1)).' kg today':'No weight recorded today'.($stats['currentWeight']!==null?' · Last: '.e(number_format($stats['currentWeight'],1)).' kg':'') ?></p></div><button type="button" data-open-weight-modal class="btn-info min-h-0 px-3 py-2 text-sm"><?= $stats['todayWeight']!==null?'Update':'Add today’s' ?> weight</button></section>

<section class="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="card border-sky-900/60"><p class="text-xs text-sky-400">🏋️ Workouts this week</p><p class="metric"><?= (int)$stats['week']['sessions'] ?></p></div><div class="card border-emerald-900/60"><p class="text-xs text-emerald-400">⚖️ Current body weight</p><p class="metric"><?= $stats['currentWeight']!==null?e(number_format($stats['currentWeight'],1)).' kg':'—' ?></p></div><div class="card border-violet-900/60"><p class="text-xs text-violet-400">🏆 Personal records</p><p class="metric"><?= (int)$stats['recordCount'] ?></p></div><div class="card border-emerald-900/60"><p class="text-xs text-emerald-400">📈 Progressed this month</p><p class="metric text-emerald-400"><?= (int)$stats['progressedThisMonth'] ?></p></div></section>

<section class="card mb-6"><div class="mb-4"><h2 class="font-bold">🔥 Workout consistency</h2><p class="text-sm text-zinc-400">Small steps, repeated consistently.</p></div><div class="mb-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div class="rounded-xl bg-orange-950/25 p-3"><p class="text-xs text-orange-400">🔥 Current streak</p><p class="font-bold"><?= (int)$stats['streak'] ?> day<?= $stats['streak']===1?'':'s' ?></p></div><div class="rounded-xl bg-sky-950/25 p-3"><p class="text-xs text-sky-400">🏋️ Total workouts</p><p class="font-bold"><?= (int)$stats['totalWorkouts'] ?></p></div><div class="rounded-xl bg-violet-950/25 p-3"><p class="text-xs text-violet-400">📅 This month</p><p class="font-bold"><?= (int)$stats['monthWorkouts'] ?></p></div><div class="rounded-xl bg-emerald-950/25 p-3"><p class="text-xs text-emerald-400">🏆 Longest streak</p><p class="font-bold"><?= (int)$stats['longestStreak'] ?> day<?= $stats['longestStreak']===1?'':'s' ?></p></div></div>
  <div class="workout-calendar" role="img" aria-label="Completed workouts during the last 53 weeks">
    <div class="workout-calendar-months" aria-hidden="true"><?php foreach($heatmapCalendar['months'] as $weekIndex=>$month): ?><span style="grid-column:<?= (int)$weekIndex+1 ?>"><?= e($month) ?></span><?php endforeach; ?></div>
    <div class="workout-calendar-days" aria-hidden="true"><span>Mon</span><span></span><span>Wed</span><span></span><span>Fri</span><span></span><span></span></div>
    <div class="workout-heatmap"><?php foreach($heatmapCalendar['weeks'] as $week): ?><div class="workout-heatmap-week"><?php foreach($week['days'] as $day):$description=$day['future']?$day['label'].': upcoming':$day['label'].': '.$day['count'].' completed workout'.($day['count']===1?'':'s');?><span class="workout-heatmap-cell <?= $day['future']?'is-future':'heatmap-level-'.$day['level'] ?>" title="<?= e($description) ?>" aria-label="<?= e($description) ?>"></span><?php endforeach; ?></div><?php endforeach; ?></div>
    <div class="workout-calendar-legend" aria-label="Workout activity intensity"><span>Less</span><?php for($level=0;$level<=4;$level++): ?><span class="workout-heatmap-cell heatmap-level-<?= $level ?>" aria-hidden="true"></span><?php endfor; ?><span>More</span></div>
  </div>
</section>

<div class="grid gap-6 lg:grid-cols-2"><section class="card"><div class="mb-3 flex justify-between"><h2 class="font-bold">📅 Recent workouts</h2><a class="text-sm text-sky-400" href="/workouts">View history</a></div><?php if(!$sessions): ?><p class="text-zinc-400">No workouts recorded yet.</p><?php endif; ?><?php foreach($sessions as $workout): ?><a href="/workouts/<?= (int)$workout['id'] ?>" class="group flex items-center justify-between gap-3 rounded-xl border-t border-zinc-800 px-2 py-3 transition first:border-0 hover:bg-zinc-800/70"><div><strong><?= e($workout['session_type']) ?></strong><p class="text-sm text-zinc-400"><?= e(date('M j, Y',strtotime($workout['performed_at']))) ?> · <?= (int)$workout['working_set_count'] ?> working sets<?php if($workout['body_weight_kg']): ?> · <?= e(format_number($workout['body_weight_kg'])) ?> kg<?php endif; ?></p></div><span class="flex h-8 w-8 items-center justify-center rounded-full bg-zinc-800 text-sky-400 transition group-hover:bg-sky-700 group-hover:text-white">→</span></a><?php endforeach; ?></section>
<section class="card"><div class="mb-3 flex items-center justify-between"><h2 class="font-bold">🏆 Personal records</h2><a class="text-sm text-violet-400" href="/exercises">View exercises</a></div><?php if(!$stats['records']): ?><p class="text-zinc-400">Your records will appear here.</p><?php endif; ?><?php foreach($stats['records'] as $record): ?><a href="/exercises/<?= (int)$record['id'] ?>" class="flex justify-between rounded-xl border-t border-zinc-800 px-2 py-3 first:border-0 hover:bg-zinc-800/70"><span><?= e($record['name']) ?></span><strong class="text-emerald-400"><?= e(format_number($record['max_weight'])) ?> kg</strong></a><?php endforeach; ?></section></div>

<section class="mt-6"><div class="mb-3"><h2 class="text-lg font-bold">📈 Exercise progress</h2><p class="text-sm text-zinc-400">Latest best set compared with your previous workout.</p></div><div class="grid gap-3 md:grid-cols-2"><?php foreach($stats['progress'] as $item):$hasPrevious=$item['previous_weight']!==null;$weightDiff=$hasPrevious?(float)$item['latest_weight']-(float)$item['previous_weight']:null;$repDiff=$hasPrevious?(int)$item['latest_reps']-(int)$item['previous_reps']:null;$improved=$hasPrevious&&($weightDiff>0||($weightDiff===0.0&&$repDiff>0));$regressed=$hasPrevious&&($weightDiff<0||($weightDiff===0.0&&$repDiff<0));$newRecord=$hasPrevious&&$weightDiff>0&&(float)$item['latest_weight']>=(float)$item['all_time_max'];?><a href="/exercises/<?= (int)$item['id'] ?>" class="card block transition hover:-translate-y-0.5 hover:border-zinc-700"><div class="mb-3 flex justify-between gap-2"><strong><?= e($item['name']) ?></strong><span class="text-xs text-zinc-500"><?= e(date('M j',strtotime($item['performed_at']))) ?></span></div><div class="grid grid-cols-2 gap-3 text-sm"><div><p class="text-xs text-zinc-500">Latest</p><p class="font-bold"><?= e(number_format((float)$item['latest_weight'],2)) ?> kg × <?= (int)$item['latest_reps'] ?></p></div><div><p class="text-xs text-zinc-500">Previous</p><p class="font-bold"><?= $hasPrevious?e(number_format((float)$item['previous_weight'],2)).' kg × '.(int)$item['previous_reps']:'—' ?></p></div></div><p class="mt-3 text-sm font-bold <?= !$hasPrevious?'text-sky-400':($improved?'text-emerald-400':($regressed?'text-red-400':'text-zinc-500')) ?>"><?php if(!$hasPrevious): ?>🔵 First entry<?php elseif($newRecord): ?>🟢 New personal record · +<?= e(number_format($weightDiff,2)) ?> kg<?php elseif($weightDiff>0): ?>🟢 +<?= e(number_format($weightDiff,2)) ?> kg<?php elseif($weightDiff<0): ?>🔴 Regression · <?= e(number_format($weightDiff,2)) ?> kg<?php elseif($repDiff>0): ?>🟢 +<?= (int)$repDiff ?> repetition<?= $repDiff===1?'':'s' ?><?php elseif($repDiff<0): ?>🔴 Regression · <?= (int)$repDiff ?> repetitions<?php else: ?>⚪ No change<?php endif; ?></p></a><?php endforeach; ?><?php if(!$stats['progress']): ?><div class="card text-zinc-400">Complete a workout to begin tracking progress.</div><?php endif; ?></div></section>

<?php if($stats['weight']): ?><section class="card mt-6"><div class="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-semibold text-sky-400">⚖️ BODY WEIGHT</p><p class="text-3xl font-black"><?= e(number_format($stats['currentWeight'],1)) ?> kg</p><p class="text-sm text-zinc-500">Previous: <?= $stats['previousWeight']!==null?e(number_format($stats['previousWeight'],1)).' kg':'—' ?></p></div><div class="flex flex-wrap gap-2 text-sm"><?php foreach(['Latest'=>$stats['entryWeightChange'],'7 days'=>$stats['weeklyWeightTrend'],'Month'=>$stats['monthlyWeightTrend']] as $label=>$trend): ?><span class="rounded-xl bg-zinc-950 px-3 py-2 <?= e($trendColor($trend)) ?>"><?= e($label) ?>: <?= $trend===null?'—':(($trend>0?'+':'').number_format($trend,1).' kg') ?></span><?php endforeach; ?></div></div><div class="h-64"><canvas data-chart='<?= e(json_encode(['type'=>'line','label'=>'Weight (kg)','rows'=>$stats['weight']])) ?>'></canvas></div></section><?php endif; ?>
