<?php
$title='Measurements';
$steps=[
 ['field'=>'measured_on','name'=>'Date','icon'=>'📅','unit'=>'','guide'=>'Choose the date of this monthly check-up.','region'=>'body'],
 ['field'=>'neck_cm','name'=>'Neck','icon'=>'📏','unit'=>'cm','guide'=>'Measure around the middle of your neck.','region'=>'neck'],
 ['field'=>'chest_cm','name'=>'Chest','icon'=>'📏','unit'=>'cm','guide'=>'Measure around the widest point of your chest.','region'=>'chest'],
 ['field'=>'waist_cm','name'=>'Waist','icon'=>'📏','unit'=>'cm','guide'=>'Measure around the narrowest point after breathing out normally.','region'=>'waist'],
 ['field'=>'arm_cm','name'=>'Arm','icon'=>'💪','unit'=>'cm','guide'=>'Measure around the widest part of your relaxed arm.','region'=>'arm'],
 ['field'=>'thigh_cm','name'=>'Thigh','icon'=>'🦵','unit'=>'cm','guide'=>'Measure around the widest part of your thigh.','region'=>'thigh'],
 ['field'=>'calf_cm','name'=>'Calf','icon'=>'🦵','unit'=>'cm','guide'=>'Measure around the widest part of your calf.','region'=>'calf'],
 ['field'=>'weight_kg','name'=>'Body weight','icon'=>'⚖️','unit'=>'kg','guide'=>'Measure under the same conditions each month whenever possible.','region'=>'body'],
];
$initial=$current??array_fill_keys(array_column($steps,'field'),'');$initial['measured_on']=date('Y-m-d');if(($initial['weight_kg']??'')===''||$initial['weight_kg']===null)$initial['weight_kg']=$defaultWeight??'';$completed=(bool)$current;$nextReminder=date('Y-m-d',strtotime('first day of next month'));
?>
<div class="mx-auto max-w-5xl" data-measurement-page data-previous='<?= e(json_encode($previous?:[],JSON_UNESCAPED_UNICODE)) ?>' data-series='<?= e(json_encode($series,JSON_UNESCAPED_UNICODE)) ?>'>
  <section id="measurement-landing">
    <header class="mb-6"><p class="text-sm font-semibold text-emerald-400">MONTHLY CHECK-UP</p><h1 class="mt-1 text-3xl font-black">📏 Monthly Body Check-up</h1><p class="mt-2 text-zinc-400">Track your progress once a month in a calm, guided check-up.</p></header>

    <section class="mb-6 overflow-hidden rounded-3xl border <?= $completed?'border-emerald-800/70':'border-amber-800/60' ?> bg-gradient-to-br <?= $completed?'from-emerald-950/50':'from-amber-950/35' ?> via-zinc-900 to-zinc-950 p-5 sm:p-7">
      <div class="grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p class="text-sm font-bold <?= $completed?'text-emerald-400':'text-amber-400' ?>"><?= $completed?'✅ CHECK-UP COMPLETED':'📏 MEASUREMENTS DUE' ?></p><h2 class="mt-2 text-2xl font-black"><?= $completed?'This month is recorded':'Ready for your monthly check-up?' ?></h2><p class="mt-2 max-w-xl text-zinc-400"><?= $completed?'You can review or gently correct any value whenever needed.':'One body part at a time. No pressure, and every measurement can be skipped.' ?></p><div class="mt-5 grid max-w-xl grid-cols-2 gap-3 text-sm sm:grid-cols-3"><div class="rounded-xl bg-black/20 p-3"><p class="text-xs text-zinc-500">Estimated time</p><strong>2 minutes</strong></div><div class="rounded-xl bg-black/20 p-3"><p class="text-xs text-zinc-500">Last measurement</p><strong><?= $last?e(date('M j, Y',strtotime($last['measured_on']))):'None yet' ?></strong></div><div class="col-span-2 rounded-xl bg-black/20 p-3 sm:col-span-1"><p class="text-xs text-zinc-500">Next reminder</p><strong><?= e(date('M j, Y',strtotime($nextReminder))) ?></strong></div></div></div><button type="button" data-start-checkup class="<?= $completed?'btn-secondary':'btn-reminder' ?> w-full md:w-auto"><?= $completed?'Review this month':'📏 Start measurements' ?></button></div>
    </section>

    <?php if(!$measurements): ?>
      <section class="card mb-6 py-10 text-center"><div class="text-5xl">📏</div><h2 class="mt-4 text-xl font-black">No measurements yet.</h2><p class="mx-auto mt-2 max-w-md text-zinc-400">Complete your first monthly check-up to begin tracking your body progress.</p><button type="button" data-start-checkup class="btn-primary mt-5">Start measurements</button></section>
    <?php else: ?>
      <section class="mb-8"><div class="mb-4"><h2 class="text-xl font-black">📅 Check-up history</h2><p class="text-sm text-zinc-500">A simple monthly view of your consistency.</p></div><div class="grid gap-3 md:grid-cols-2"><?php foreach($measurements as $index=>$measurement):$prior=$measurements[$index+1]??null; ?>
        <details class="group card p-0"><summary class="flex min-h-20 cursor-pointer list-none items-center gap-3 p-4"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-950 text-xl">📅</span><div class="flex-1"><h3 class="font-black"><?= e(date('F Y',strtotime($measurement['measured_on']))) ?></h3><p class="text-sm text-zinc-500"><?php $preview=[];if($measurement['weight_kg']!==null)$preview[]='⚖️ '.number_format((float)$measurement['weight_kg'],1).' kg';if($measurement['waist_cm']!==null)$preview[]='Waist '.number_format((float)$measurement['waist_cm'],1).' cm';echo e(implode(' · ',$preview)?:'Date recorded'); ?></p></div><span class="flex h-10 w-10 items-center justify-center rounded-full text-zinc-500 transition group-open:rotate-180">⌄</span></summary>
          <div class="border-t border-zinc-800 p-4"><div class="grid grid-cols-2 gap-2 sm:grid-cols-3"><?php foreach($steps as $step):if($step['field']==='measured_on'||$measurement[$step['field']]===null)continue;$diff=$prior&&$prior[$step['field']]!==null?(float)$measurement[$step['field']]-(float)$prior[$step['field']]:null; ?><div class="rounded-xl bg-zinc-950 p-3"><p class="text-xs text-zinc-500"><?= e($step['icon'].' '.$step['name']) ?></p><strong><?= e(number_format((float)$measurement[$step['field']],1)) ?> <?= e($step['unit']) ?></strong><?php if($diff!==null): ?><p class="text-xs <?= $diff>0?'text-emerald-400':($diff<0?'text-red-400':'text-zinc-500') ?>"><?= $diff>0?'+':'' ?><?= e(number_format($diff,1)) ?> <?= e($step['unit']) ?></p><?php endif; ?></div><?php endforeach; ?></div><?php if($measurement['notes']): ?><p class="mt-3 text-sm text-zinc-400"><?= e($measurement['notes']) ?></p><?php endif; ?><form method="post" action="<?= e(route('measurements.destroy',['id'=>$measurement['id']])) ?>" class="mt-4 text-right" data-confirm="Delete this monthly check-up? This cannot be undone." data-confirm-button="Delete check-up"><?= csrf_field() ?><button class="text-sm font-semibold text-red-400">Delete</button></form></div>
        </details>
      <?php endforeach; ?></div></section>

      <section class="card"><div class="mb-4"><p class="text-sm font-semibold text-violet-400">📈 PROGRESS</p><h2 class="text-xl font-black">Body evolution</h2></div><div class="top-nav mb-5 flex gap-2 overflow-x-auto pb-2" role="tablist"><?php foreach($series as $field=>$data): ?><button type="button" data-measurement-chart-tab="<?= e($field) ?>" class="whitespace-nowrap rounded-full bg-zinc-800 px-4 py-2 text-sm font-semibold text-zinc-400"><?= e($data['label']) ?></button><?php endforeach; ?></div><div class="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs text-zinc-500">Current</p><p id="measurement-chart-current" class="text-3xl font-black">—</p></div><p id="measurement-chart-change" class="text-sm font-semibold text-zinc-500"></p></div><div class="h-72"><canvas id="measurement-progress-chart"></canvas></div></section>
    <?php endif; ?>
  </section>

  <section id="measurement-wizard" class="hidden">
    <form method="post" action="<?= e(route('measurements.store')) ?>" id="measurement-wizard-form"><?= csrf_field() ?>
      <div class="mx-auto max-w-3xl"><div class="mb-4 flex items-center justify-between"><button type="button" data-exit-checkup class="text-sm font-semibold text-zinc-400 hover:text-white">← Save nothing & exit</button><span id="measurement-step-label" class="text-sm text-zinc-500"></span></div><div class="mb-6 h-2 overflow-hidden rounded-full bg-zinc-800"><div id="measurement-progress" class="h-full rounded-full bg-emerald-500 transition-all"></div></div>
        <div class="grid min-h-[560px] items-center gap-6 rounded-3xl border border-zinc-800 bg-zinc-900 p-5 shadow-2xl md:grid-cols-2 md:p-8">
          <div class="mx-auto w-full max-w-[230px]" aria-hidden="true"><svg viewBox="0 0 180 360" class="h-auto w-full"><circle cx="90" cy="34" r="25" fill="#27272a"/><rect x="83" y="58" width="14" height="20" rx="6" fill="#3f3f46"/><path d="M55 78 Q90 62 125 78 L139 181 Q125 205 116 220 L108 338 H82 L73 220 Q55 194 41 181 Z" fill="#27272a"/><path d="M54 88 L25 190" stroke="#27272a" stroke-width="22" stroke-linecap="round"/><path d="M126 88 L155 190" stroke="#27272a" stroke-width="22" stroke-linecap="round"/><g fill="none" stroke="#34d399" stroke-width="8" opacity="0" data-body-region="neck"><path d="M75 68 Q90 77 105 68"/></g><g fill="none" stroke="#34d399" stroke-width="8" opacity="0" data-body-region="chest"><path d="M55 104 Q90 125 125 104"/></g><g fill="none" stroke="#34d399" stroke-width="8" opacity="0" data-body-region="waist"><path d="M48 165 Q90 180 132 165"/></g><g fill="none" stroke="#34d399" stroke-width="8" opacity="0" data-body-region="arm"><path d="M35 128 L25 166"/></g><g fill="none" stroke="#34d399" stroke-width="9" opacity="0" data-body-region="thigh"><path d="M72 225 L79 270"/></g><g fill="none" stroke="#34d399" stroke-width="9" opacity="0" data-body-region="calf"><path d="M79 286 L83 323"/></g><g fill="none" stroke="#34d399" stroke-width="5" opacity="0" data-body-region="body"><rect x="18" y="4" width="144" height="344" rx="65"/></g></svg></div>
          <div><?php foreach($steps as $index=>$step): ?><section data-measurement-step="<?= $index ?>" data-field="<?= e($step['field']) ?>" data-unit="<?= e($step['unit']) ?>" data-region="<?= e($step['region']) ?>" class="hidden"><p class="text-sm font-bold text-emerald-400"><?= e(strtoupper($step['name'])) ?></p><h2 class="mt-1 text-3xl font-black"><?= e($step['icon'].' '.$step['name']) ?></h2><p class="mt-3 leading-relaxed text-zinc-400"><?= e($step['guide']) ?></p><?php if($step['field']!=='measured_on'): ?><div class="mt-5 rounded-xl bg-zinc-950 p-3"><p class="text-xs text-zinc-500">Previous</p><p class="font-bold" data-previous-display>—</p></div><?php endif; ?><div class="mt-5"><label for="measurement-<?= e($step['field']) ?>">Current<?= $step['field']==='measured_on'?' date':'' ?></label><div class="relative"><input id="measurement-<?= e($step['field']) ?>" name="<?= e($step['field']) ?>" <?= $step['field']==='measured_on'?'type="date" required':'type="number" inputmode="decimal" min="0" step="0.1" placeholder="Tap to enter"' ?> value="<?= e($initial[$step['field']]??'') ?>" class="h-16 pr-14 text-center text-3xl font-black"><?php if($step['unit']): ?><span class="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 font-bold text-zinc-500"><?= e($step['unit']) ?></span><?php endif; ?></div><p class="mt-3 min-h-6 text-center text-sm font-bold" data-live-difference></p></div></section><?php endforeach; ?>
            <section id="measurement-finish" class="hidden"><p class="text-5xl">✅</p><h2 class="mt-3 text-3xl font-black">Monthly check-up complete</h2><p class="mt-2 text-zinc-400">Showing up consistently matters more than any single number.</p><div id="measurement-summary" class="mt-5 grid grid-cols-2 gap-2"></div><div class="mt-4"><label for="measurement-notes">Optional note</label><textarea id="measurement-notes" name="notes" rows="2" placeholder="Anything you want to remember?"><?= e($current['notes']??'') ?></textarea></div></section>
          </div>
        </div><div class="sticky bottom-0 mt-4 grid grid-cols-2 gap-3 bg-zinc-950/95 py-3 backdrop-blur"><button type="button" id="measurement-previous" class="btn-secondary">Previous</button><button type="button" id="measurement-next" class="btn-primary">Next</button><button id="measurement-save" class="btn-primary col-span-2 hidden">Save measurements</button></div>
      </div>
    </form>
  </section>
</div>
<script defer src="<?= e(asset('assets/js/measurements.js')) ?>"></script>
