<?php
require dirname(__DIR__).'/vendor/autoload.php';Dotenv\Dotenv::createImmutable(dirname(__DIR__))->load();
use App\Core\Database;use App\Models\WorkoutTemplate;use App\Services\ActiveWorkoutService;
$db=Database::connection();$service=new ActiveWorkoutService();if($service->active())throw new RuntimeException('An active workout already exists; workout-mode test was not run.');$template=WorkoutTemplate::forDay(7)??throw new RuntimeException('Leg workout plan is missing.');$oldPolicy=$db->query("SELECT setting_value FROM settings WHERE setting_key='warmup_default_behavior'")->fetchColumn()?:'ask';$db->prepare("INSERT INTO settings(setting_key,setting_value) VALUES('warmup_default_behavior','ask') ON DUPLICATE KEY UPDATE setting_value='ask'")->execute();$state=$service->start((int)$template['id']);$sessionId=(int)$state['session']['id'];$parallelSessionId=null;
try{
    if($state['current']['name']!=='Leg Press'||(int)$state['current']['target_set_count']!==3||!$state['warmupPrompt'])throw new RuntimeException('Workout plan was not initialized with an optional warm-up choice.');
    $service->decideWarmup(true);$state=$service->active();if($state['currentSet']['set_type']!=='warmup'||$state['warmupPrompt'])throw new RuntimeException('Warm-up choice was not persisted.');
    $replacement=$state['replacementCandidates'][0]??null;if($replacement){$originalExerciseId=(int)$state['current']['exercise_id'];$service->replaceExercise((int)$replacement['id']);$replaced=$service->active();if((int)$replaced['current']['exercise_id']!==(int)$replacement['id'])throw new RuntimeException('Exercise replacement was not persisted.');if(!$replaced['warmupPrompt'])throw new RuntimeException('Exercise replacement did not reset the warm-up choice.');$service->replaceExercise($originalExerciseId);$state=$service->active();if(!$state['warmupPrompt'])throw new RuntimeException('Warm-up choice was not reset after restoring an exercise.');}
    $remainingIds=array_map(fn($exercise)=>(int)$exercise['id'],$state['remainingExercises']);$reordered=array_reverse($remainingIds);$service->reorderExercises($reordered);$ordered=$service->active();if((int)$ordered['current']['id']!==$reordered[0])throw new RuntimeException('Saving a new order did not activate its first exercise.');$service->reorderExercises($remainingIds);$state=$service->active();
    $added=$service->addSet();$state=$service->active();if((int)$state['current']['target_set_count']!==4||(int)$state['extraSets'][0]['id']!==$added['set_id'])throw new RuntimeException('An extra set was not persisted.');$service->removeSet($added['set_id']);$state=$service->active();if((int)$state['current']['target_set_count']!==3||$state['extraSets'])throw new RuntimeException('An extra set was not removed.');
    $service->bodyWeight(80.5);$state=$service->active();if((float)$state['session']['body_weight_kg']!==80.5)throw new RuntimeException('Workout body weight was not saved.');
    $sets=0;$exerciseCompletions=0;$dropSetId=null;while(($state=$service->active())&&$state['current']){if($state['warmupPrompt']){$service->decideWarmup(true);$state=$service->active();}$data=['weight_kg'=>$state['defaultWeight']?:50,'repetitions'=>12];if($state['currentSet']['set_type']==='working'&&$dropSetId===null){$data['segments']=json_encode([['weight_kg'=>55,'repetitions'=>5],['weight_kg'=>45,'repetitions'=>4]]);}$result=$service->completeSet($data);$sets++;if(isset($data['segments'])){$dropSetId=$result['set_id'];$next=$service->active();if((float)$next['defaultWeight']!==55.0)throw new RuntimeException('The latest working-set weight was not reused.');$segmentStats=$db->query('SELECT COUNT(*) segment_count,SUM(weight_kg*repetitions) volume FROM exercise_set_segments WHERE exercise_set_id='.(int)$dropSetId)->fetch();if((int)$segmentStats['segment_count']!==2||(float)$segmentStats['volume']!==455.0)throw new RuntimeException('Drop-set segments or volume are incorrect.');}if($sets===1&&$replacement){try{$service->replaceExercise((int)$replacement['id']);throw new RuntimeException('A replacement was allowed after completing a set.');}catch(RuntimeException $exception){if($exception->getMessage()==='A replacement was allowed after completing a set.')throw $exception;}}if($result['status']==='exercise_completed')$exerciseCompletions++;if($sets>24)throw new RuntimeException('Workout did not advance.');}
    $summary=$service->summary();if($sets!==16||count($summary['summary'])!==4||$exerciseCompletions!==3)throw new RuntimeException('Workout completion state is incorrect.');$finished=$service->finish('Automated workout-mode test');if($finished!==$sessionId)throw new RuntimeException('Workout was not finished.');
    $db->prepare("UPDATE settings SET setting_value='add' WHERE setting_key='warmup_default_behavior'")->execute();$automatic=$service->start((int)$template['id']);if($automatic['warmupPrompt']||$automatic['currentSet']['set_type']!=='warmup')throw new RuntimeException('Automatic warm-up policy failed.');$service->completeSet(['weight_kg'=>20,'repetitions'=>10]);$warmupOnly=$service->finishEarly();if((int)$warmupOnly['skipped']!==4)throw new RuntimeException('A warm-up-only exercise incorrectly counted as completed.');$service->cancel();$db->prepare("UPDATE settings SET setting_value='never' WHERE setting_key='warmup_default_behavior'")->execute();$without=$service->start((int)$template['id']);if($without['warmupPrompt']||$without['currentSet']['set_type']!=='working')throw new RuntimeException('No-warm-up policy failed.');$service->cancel();
    $parallel=$service->start((int)$template['id']);$parallelSessionId=(int)$parallel['session']['id'];$firstId=(int)$parallel['current']['id'];$secondId=(int)$parallel['remainingExercises'][1]['id'];$service->completeSet(['weight_kg'=>'17.5','repetitions'=>8]);$service->switchExercise($secondId);$parallel=$service->active();if((int)$parallel['current']['id']!==$secondId||count($parallel['activeExercises'])!==2)throw new RuntimeException('Parallel exercises were not kept active.');$first=array_values(array_filter($parallel['activeExercises'],fn($exercise)=>(int)$exercise['id']===$firstId))[0]??null;if(!$first||(int)$first['rest_remaining']<=0)throw new RuntimeException('The first exercise did not keep its independent rest timer.');$service->completeSet(['weight_kg'=>'22.5','repetitions'=>8]);$service->switchExercise($firstId);$parallel=$service->active();if((float)$parallel['defaultWeight']!==17.5||(int)$parallel['current']['current_set_position']!==2)throw new RuntimeException('Switching exercises did not preserve progress or decimal weight.');$early=$service->finishEarly();if((int)$early['skipped']!==2)throw new RuntimeException('Finishing early did not mark untouched exercises as skipped.');$summary=$service->summary();if((int)$summary['skippedCount']!==2||$summary['current']!==null)throw new RuntimeException('Early-finish summary is incorrect.');$service->finish('Parallel exercise test');
    echo "✓ Workout Mode: warm-ups, drop sets, decimal weights, dynamic sets, parallel exercises, independent timers, early finish and completion\n";
}finally{$db->prepare('DELETE FROM workout_sessions WHERE id IN (?,?)')->execute([$sessionId,$parallelSessionId??0]);$db->prepare("DELETE FROM body_weight_entries WHERE recorded_on=CURRENT_DATE AND source='workout'")->execute();$db->prepare("UPDATE settings SET setting_value=? WHERE setting_key='warmup_default_behavior'")->execute([$oldPolicy]);}
