<?php $editing=isset($exercise);$title=$editing?'Edit exercise':'Add exercise'; ?>
<div class="mb-6"><p class="text-sm font-semibold text-emerald-400">EXERCISE LIBRARY</p><h1 class="mt-1 text-3xl font-black"><?= e($title) ?></h1></div>
<form method="post" action="<?= e($editing?route('exercises.update',['id'=>$exercise['id']]):route('exercises.store')) ?>" class="card max-w-2xl space-y-4"><?= csrf_field() ?>
  <div><label>Name</label><input required name="name" value="<?= e($exercise['name']??'') ?>" placeholder="e.g. Dumbbell Bench Press"></div>
  <div class="grid gap-4 sm:grid-cols-2"><div><label>Muscle group</label><select required name="muscle_group_id"><option value="">Choose</option><?php foreach($muscleGroups as $group): ?><option value="<?= (int)$group['id'] ?>" <?= (int)($exercise['muscle_group_id']??0)===(int)$group['id']?'selected':'' ?>><?= e($group['name']) ?></option><?php endforeach; ?></select></div><div><label>Equipment</label><select name="equipment_id"><option value="">No equipment</option><?php foreach($equipment as $item): ?><option value="<?= (int)$item['id'] ?>" <?= (int)($exercise['equipment_id']??0)===(int)$item['id']?'selected':'' ?>><?= e($item['name']) ?></option><?php endforeach; ?></select></div></div>
  <div class="grid gap-4 sm:grid-cols-2"><div><label>Variant</label><input name="variant" value="<?= e($exercise['variant']??'') ?>"></div><div><label>Recommended rest (seconds)</label><input required type="number" min="0" name="recommended_rest_seconds" value="<?= e($exercise['recommended_rest_seconds']??90) ?>"></div></div>
  <div><label>Notes</label><textarea name="notes" rows="3"><?= e($exercise['notes']??'') ?></textarea></div><button class="btn-primary"><?= $editing?'Save changes':'Create exercise' ?></button>
</form>
<?php if($editing): ?><form method="post" action="<?= e(route('exercises.destroy',['id'=>$exercise['id']])) ?>" class="mt-4 max-w-2xl" data-confirm="Archive this exercise? Its history will be kept." data-confirm-button="Archive exercise"><?= csrf_field() ?><button class="btn-danger">Archive exercise</button></form><?php endif; ?>
