<?php $editing=isset($exercise);$title=$editing?'Edit exercise':'Add exercise';$isDumbbell=($exercise['equipment']??'')==='Dumbbells'; ?>
<div class="mb-6"><p class="text-sm font-semibold text-emerald-400">EXERCISE LIBRARY</p><h1 class="mt-1 text-3xl font-black"><?= e($title) ?></h1></div>
<form method="post" action="<?= e($editing?route('exercises.update',['id'=>$exercise['id']]):route('exercises.store')) ?>" class="card max-w-2xl space-y-4"><?= csrf_field() ?>
  <div><label>Name</label><input required name="name" value="<?= e($exercise['name']??'') ?>" placeholder="e.g. Dumbbell Bench Press"></div>
  <div class="grid gap-4 sm:grid-cols-2"><div><label>Muscle group</label><select required name="muscle_group_id"><option value="">Choose</option><?php foreach($muscleGroups as $group): ?><option value="<?= (int)$group['id'] ?>" <?= (int)($exercise['muscle_group_id']??0)===(int)$group['id']?'selected':'' ?>><?= e($group['name']) ?></option><?php endforeach; ?></select></div><div><label>Equipment</label><select name="equipment_id" data-exercise-equipment><option value="">No equipment</option><?php foreach($equipment as $item): ?><option value="<?= (int)$item['id'] ?>" data-equipment-name="<?= e($item['name']) ?>" <?= (int)($exercise['equipment_id']??0)===(int)$item['id']?'selected':'' ?>><?= e($item['name']) ?></option><?php endforeach; ?></select></div></div>
  <section data-dumbbell-weight-settings class="<?= $isDumbbell?'':'hidden' ?> rounded-2xl border border-violet-900/60 bg-violet-950/20 p-4">
    <p class="text-sm font-bold text-violet-300">Dumbbell weight mode</p><p class="mt-1 text-sm text-zinc-400">Choose how future weights are entered and displayed for this exercise.</p>
    <div class="mt-4 grid gap-2"><label class="flex cursor-pointer items-start gap-3 rounded-xl bg-zinc-950/60 p-3"><input type="radio" name="load_semantics" value="per_dumbbell" <?= ($exercise['load_semantics']??'per_dumbbell')==='per_dumbbell'?'checked':'' ?>><span><strong class="block">Weight per dumbbell <span class="text-emerald-400">(recommended)</span></strong><span class="text-xs text-zinc-500">Example: enter 17.5 kg when each dumbbell weighs 17.5 kg.</span></span></label><label class="flex cursor-pointer items-start gap-3 rounded-xl bg-zinc-950/60 p-3"><input type="radio" name="load_semantics" value="total" <?= ($exercise['load_semantics']??'')==='total'?'checked':'' ?>><span><strong class="block">Total combined weight</strong><span class="text-xs text-zinc-500">Example: enter 35 kg for two 17.5 kg dumbbells.</span></span></label></div>
    <?php if($editing): ?><div data-history-weight-action class="mt-4 border-t border-violet-900/50 pt-4"><p class="text-sm font-semibold">If the mode changes</p><label class="mt-2 flex items-start gap-3 text-sm"><input type="radio" name="history_weight_action" value="keep" checked><span><strong>Keep existing history unchanged</strong> <span class="text-emerald-400">(recommended)</span><span class="block text-xs text-zinc-500">Past values keep their original number and recorded mode.</span></span></label><label class="mt-3 flex items-start gap-3 text-sm"><input type="radio" name="history_weight_action" value="convert"><span><strong>Convert historical values</strong><span class="block text-xs text-zinc-500">Past values are multiplied or divided by two to match the new mode.</span></span></label></div><?php endif; ?>
  </section>
  <div class="grid gap-4 sm:grid-cols-2"><div><label>Variant</label><input name="variant" value="<?= e($exercise['variant']??'') ?>"></div><div><label>Recommended rest (seconds)</label><input required type="number" min="0" name="recommended_rest_seconds" value="<?= e($exercise['recommended_rest_seconds']??90) ?>"></div></div>
  <div><label>Notes</label><textarea name="notes" rows="3"><?= e($exercise['notes']??'') ?></textarea></div><button class="btn-primary"><?= $editing?'Save changes':'Create exercise' ?></button>
</form>
<?php if($editing): ?><form method="post" action="<?= e(route('exercises.destroy',['id'=>$exercise['id']])) ?>" class="mt-4 max-w-2xl" data-confirm="Archive this exercise? Its history will be kept." data-confirm-button="Archive exercise"><?= csrf_field() ?><button class="btn-danger">Archive exercise</button></form><?php endif; ?>
