<?php
$title='Exercises';$groups=[];foreach($exercises as $exercise)$groups[$exercise['muscle_group']][]=$exercise;
$icons=['Neck'=>'🧠','Shoulders'=>'🏋️','Chest'=>'💪','Back'=>'🔷','Biceps'=>'💪','Triceps'=>'💪','Forearms'=>'✊','Lower Back'=>'🔸','Legs'=>'🦵','Calves'=>'🦵'];
$query=function(array $changes)use($filters):string{$values=array_merge($filters,$changes);$values=array_filter($values,fn($value)=>$value!==''&&$value!=='all');return route('exercises.index').($values?'?'.http_build_query($values):'');};
?>
<header class="mb-6 flex items-start justify-between gap-4"><div><p class="text-sm font-semibold text-emerald-400">TRAINING LIBRARY</p><h1 class="mt-1 text-3xl font-black">Exercises</h1><p class="mt-2 text-zinc-400">Manage your training library and exercise settings.</p></div><a href="<?= e(route('exercises.create')) ?>" class="btn-primary shrink-0"><span class="sm:hidden">＋</span><span class="hidden sm:inline">＋ Add exercise</span></a></header>

<form method="get" action="<?= e(route('exercises.index')) ?>" class="card mb-4 grid gap-3 p-3 md:grid-cols-[1fr_180px_180px_auto]">
  <label class="sr-only" for="exercise-search">Search exercises</label><input id="exercise-search" name="search" type="search" placeholder="Search exercises…" value="<?= e($filters['search']) ?>">
  <select name="scope" aria-label="Exercise scope"><option value="all">All exercises</option><option value="program" <?= $filters['scope']==='program'?'selected':'' ?>>In my program</option><option value="recent" <?= $filters['scope']==='recent'?'selected':'' ?>>Used recently</option></select>
  <select name="equipment" aria-label="Equipment"><option value="">All equipment</option><?php foreach($equipmentOptions as $equipment): ?><option value="<?= (int)$equipment['id'] ?>" <?= (string)$filters['equipment']===(string)$equipment['id']?'selected':'' ?>><?= e($equipment['name']) ?></option><?php endforeach; ?></select>
  <button class="btn-info min-h-0">Filter</button>
</form>

<nav class="top-nav mb-5 flex gap-2 overflow-x-auto pb-2" aria-label="Muscle groups"><a href="<?= e($query(['muscle'=>''])) ?>" class="whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold <?= $filters['muscle']===''?'bg-emerald-700 text-white':'bg-zinc-900 text-zinc-400 hover:text-white' ?>">All</a><?php foreach($muscleGroups as $muscle): ?><a href="<?= e($query(['muscle'=>$muscle])) ?>" data-muscle-link="<?= e($muscle) ?>" class="whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold <?= $filters['muscle']===$muscle?'bg-emerald-700 text-white':'bg-zinc-900 text-zinc-400 hover:text-white' ?>"><?= e($muscle) ?></a><?php endforeach; ?></nav>

<?php if(!$exercises): ?><section class="card py-12 text-center"><div class="text-5xl">🔎</div><h2 class="mt-4 text-xl font-black">No exercises found.</h2><p class="mt-2 text-zinc-400">Try another search or remove a filter.</p><a href="<?= e(route('exercises.index')) ?>" class="btn-secondary mt-5 inline-flex">Clear filters</a></section><?php else: ?>
<div class="space-y-3" data-exercise-library><?php $groupIndex=0;foreach($groups as $group=>$items):$open=$filters['muscle']===$group||($filters['muscle']===''&&$groupIndex===0); ?>
  <details id="muscle-<?= e(strtolower(str_replace(' ','-',$group))) ?>" data-muscle-group="<?= e($group) ?>" class="group overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900" <?= $open?'open':'' ?>>
    <summary class="flex min-h-16 cursor-pointer list-none items-center gap-3 px-4 py-3 hover:bg-zinc-800/70"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-zinc-800 text-xl"><?= $icons[$group]??'💪' ?></span><div class="flex-1"><h2 class="font-black"><?= e($group) ?></h2><p class="text-xs uppercase tracking-wider text-zinc-500"><?= count($items) ?> exercise<?= count($items)===1?'':'s' ?></p></div><span class="flex h-10 w-10 items-center justify-center rounded-full text-zinc-400 transition group-open:rotate-180">⌄</span></summary>
    <div class="grid gap-3 border-t border-zinc-800 p-3 md:grid-cols-2"><?php foreach($items as $exercise): ?>
      <article class="relative rounded-2xl border border-zinc-800 bg-zinc-950/60 p-4 transition hover:-translate-y-0.5 hover:border-zinc-700 hover:bg-zinc-950">
        <a href="<?= e(route('exercises.show',['id'=>$exercise['id']])) ?>" class="absolute inset-0 rounded-2xl" aria-label="View <?= e($exercise['name']) ?> history"></a>
        <div class="relative pointer-events-none flex items-start gap-3"><?php if($exercise['image_path']): ?><img src="<?= e($exercise['image_path']) ?>" alt="" width="64" height="64" loading="lazy" decoding="async" class="h-16 w-16 shrink-0 rounded-xl bg-zinc-900 object-cover"><?php else: ?><span class="flex h-16 w-16 shrink-0 items-center justify-center rounded-xl bg-zinc-900 text-xl"><?= $icons[$group]??'💪' ?></span><?php endif; ?><div class="min-w-0 flex-1"><h3 class="truncate font-black"><?= e($exercise['name']) ?></h3><p class="mt-0.5 text-sm text-zinc-500"><?= e($exercise['equipment']??'No equipment') ?> · <?= e($group) ?></p><?php if($exercise['target_muscle']): ?><p class="mt-1 truncate text-xs text-zinc-600">Targets <?= e($exercise['target_muscle']) ?></p><?php endif; ?></div><?php if($exercise['in_program']): ?><span class="rounded-full bg-emerald-950 px-2 py-1 text-xs font-bold text-emerald-300">In program</span><?php endif; ?></div>
        <div class="relative pointer-events-none mt-4 flex flex-wrap gap-2 text-xs"><?php if($exercise['target_sets']): ?><span class="rounded-lg bg-zinc-900 px-2 py-1 text-zinc-300"><?= (int)$exercise['target_sets'] ?> × <?= (int)$exercise['target_reps_min'] ?>–<?= (int)$exercise['target_reps_max'] ?></span><?php endif; ?><span class="rounded-lg bg-zinc-900 px-2 py-1 text-zinc-400">⏱️ <?= (int)$exercise['recommended_rest_seconds'] ?> sec rest</span></div>
        <div class="relative pointer-events-none mt-4 border-t border-zinc-800 pt-3 text-sm"><?php if($exercise['last_weight']!==null): ?><p class="font-semibold text-emerald-400">Last: <?= e(format_number($exercise['last_weight'])) ?> kg × <?= (int)$exercise['last_reps'] ?></p><?php else: ?><p class="text-zinc-500">No performance recorded yet</p><?php endif; ?></div>
        <details class="relative z-10 mt-3 ml-auto w-fit"><summary class="flex h-10 w-10 cursor-pointer list-none items-center justify-center rounded-full bg-zinc-900 text-xl text-zinc-400 hover:text-white" aria-label="Exercise actions">⋯</summary><div class="absolute bottom-full right-0 z-30 mb-2 w-44 overflow-hidden rounded-xl border border-zinc-700 bg-zinc-900 p-1 shadow-2xl"><a class="block rounded-lg px-3 py-2 text-sm hover:bg-zinc-800" href="<?= e(route('exercises.show',['id'=>$exercise['id']])) ?>">📈 View history</a><a class="block rounded-lg px-3 py-2 text-sm hover:bg-zinc-800" href="<?= e(route('exercises.edit',['id'=>$exercise['id']])) ?>">✏️ Edit</a><form method="post" action="<?= e(route('exercises.destroy',['id'=>$exercise['id']])) ?>" data-confirm="Archive this exercise? Its complete history will be kept." data-confirm-button="Archive exercise"><?= csrf_field() ?><button class="block w-full rounded-lg px-3 py-2 text-left text-sm text-red-400 hover:bg-red-950/40">Archive</button></form></div></details>
      </article>
    <?php endforeach; ?></div>
  </details>
<?php $groupIndex++;endforeach; ?></div>
<?php endif; ?>
