<?php
$title=$exercise['name'];$record=$progress['record'];$latest=$progress['latest'];$previous=$progress['previous'];$target=$progress['target'];$stats=$progress['stats'];$change=$latest['change']??['type'=>'first','label'=>'First entry'];$instructionSteps=json_decode((string)($exercise['instruction_steps']??'[]'),true)?:[];$secondaryMuscles=json_decode((string)($exercise['secondary_muscles']??'[]'),true)?:[];
$groupIcons=['Legs'=>'🦵','Calves'=>'🦵','Shoulders'=>'🏋️','Chest'=>'💪','Back'=>'🔷','Biceps'=>'💪','Triceps'=>'💪','Forearms'=>'✊','Neck'=>'🧠','Lower Back'=>'🔸'];$icon=$groupIcons[$exercise['muscle_group']]??'💪';
$setText=fn($set)=>$set?format_number($set['weight_kg']).' kg × '.(int)$set['repetitions']:'—';
$historySetText=fn($set)=>$set?format_number($set['entered_weight_kg']??$set['weight_kg']).' kg × '.(int)$set['repetitions'].(($exercise['equipment']??'')==='Dumbbells'?' ('.(($set['load_semantics']??$exercise['load_semantics'])==='per_dumbbell'?'per dumbbell':'total').')':''):'—';
?>
<header class="mb-6 flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><p class="text-sm font-semibold text-emerald-500"><?= e($exercise['muscle_group']) ?></p><h1 class="mt-1 text-3xl font-black"><?= $icon ?> <?= e($exercise['name']) ?></h1><p class="mt-2 text-zinc-400"><?= e($exercise['equipment']??'No equipment') ?> · <?= (int)$exercise['recommended_rest_seconds'] ?> sec recommended rest<?php if(($exercise['equipment']??'')==='Dumbbells'): ?> · <?= $exercise['load_semantics']==='per_dumbbell'?'Weight per dumbbell':'Combined total weight' ?><?php endif; ?></p><?php if($target): ?><p class="mt-2 text-sm"><span class="text-zinc-500">Target:</span> <strong><?= (int)$target['set_count'] ?> × <?= (int)$target['repetitions_min'] ?>–<?= (int)$target['repetitions_max'] ?></strong> <span class="badge ml-2 bg-emerald-950 text-emerald-300">In program</span></p><?php endif; ?></div><a class="btn-secondary shrink-0" href="<?= e(route('exercises.edit',['id'=>$exercise['id']])) ?>">Edit</a></header>

<?php if($exercise['instructions']||$instructionSteps||$exercise['image_path']||$exercise['gif_path']): ?><section class="card mb-5 overflow-hidden"><div class="grid gap-5 md:grid-cols-[220px_1fr]"><div class="aspect-square overflow-hidden rounded-2xl bg-zinc-950"><?php if($exercise['gif_path']): ?><img src="<?= e($exercise['gif_path']) ?>" data-fallback="<?= e($exercise['image_path']??'') ?>" onerror="if(this.dataset.fallback){this.src=this.dataset.fallback;this.onerror=null}" alt="Demonstration of <?= e($exercise['name']) ?>" width="180" height="180" loading="lazy" decoding="async" class="h-full w-full object-cover"><?php elseif($exercise['image_path']): ?><img src="<?= e($exercise['image_path']) ?>" alt="<?= e($exercise['name']) ?>" width="180" height="180" loading="lazy" decoding="async" class="h-full w-full object-cover"><?php endif; ?></div><div><p class="text-sm font-bold text-sky-400">HOW TO PERFORM</p><h2 class="mt-1 text-xl font-black">Technique and muscles</h2><div class="mt-3 flex flex-wrap gap-2 text-sm"><?php if($exercise['target_muscle']): ?><span class="badge bg-emerald-950 text-emerald-300">Primary: <?= e($exercise['target_muscle']) ?></span><?php endif; ?><?php if($secondaryMuscles): ?><span class="badge bg-zinc-800 text-zinc-300">Secondary: <?= e(implode(', ',$secondaryMuscles)) ?></span><?php endif; ?><?php if($exercise['dataset_equipment']): ?><span class="badge bg-sky-950 text-sky-300"><?= e($exercise['dataset_equipment']) ?></span><?php endif; ?></div><?php if($instructionSteps): ?><ol class="mt-4 space-y-3"><?php foreach($instructionSteps as $index=>$step): ?><li class="flex gap-3 text-sm leading-relaxed text-zinc-300"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-zinc-800 text-xs font-bold"><?= $index+1 ?></span><span><?= e($step) ?></span></li><?php endforeach; ?></ol><?php elseif($exercise['instructions']): ?><p class="mt-4 leading-relaxed text-zinc-300"><?= e($exercise['instructions']) ?></p><?php endif; ?><?php if($exercise['media_attribution']): ?><p class="mt-4 border-t border-zinc-800 pt-3 text-xs text-zinc-600"><?= e($exercise['media_attribution']) ?></p><?php endif; ?></div></div></section><?php endif; ?>

<?php if(!$record): ?>
<section class="card py-12 text-center"><div class="text-5xl">🏋️</div><h2 class="mt-4 text-xl font-black">No performance recorded yet.</h2><p class="mx-auto mt-2 max-w-md text-zinc-400">Complete your first workout with this exercise to begin tracking progress.</p><a href="<?= e(route('workouts.create')) ?>" class="btn-primary mt-5 inline-flex">Start a workout</a></section>
<?php else: ?>
<section class="mb-5 overflow-hidden rounded-3xl border border-amber-700/60 bg-gradient-to-br from-amber-950/45 via-zinc-900 to-zinc-950 p-5 shadow-xl sm:p-7"><div class="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><p class="text-sm font-bold text-amber-400">🏆 PERSONAL RECORD</p><p class="mt-2 text-4xl font-black sm:text-5xl"><?= e($setText($record)) ?></p><p class="mt-2 text-zinc-400"><?= e(date('M j, Y',strtotime($record['completed_at']??$progress['latest']['performed_at']))) ?></p></div><div class="grid grid-cols-2 gap-2 text-sm"><div class="rounded-xl bg-black/20 p-3"><p class="text-xs text-zinc-500">Best weight</p><strong><?= e(format_number($record['weight_kg'])) ?> kg</strong></div><div class="rounded-xl bg-black/20 p-3"><p class="text-xs text-zinc-500">Best reps</p><strong><?= (int)$progress['bestRepetitions'] ?></strong></div></div></div></section>

<div class="mb-5 grid gap-4 lg:grid-cols-2">
  <section class="card border-sky-900/60"><p class="text-sm font-bold text-sky-400">📈 LATEST PERFORMANCE</p><div class="mt-4 grid grid-cols-2 gap-3"><div><p class="text-xs text-zinc-500">Latest</p><p class="mt-1 text-xl font-black"><?= e($setText($latest['best'])) ?></p><p class="text-xs text-zinc-500"><?= e(date('M j, Y',strtotime($latest['performed_at']))) ?></p></div><div><p class="text-xs text-zinc-500">Previous</p><p class="mt-1 text-xl font-black"><?= e($setText($previous['best']??null)) ?></p><p class="text-xs text-zinc-500"><?= $previous?e(date('M j, Y',strtotime($previous['performed_at']))):'No earlier session' ?></p></div></div><p class="mt-4 rounded-xl px-3 py-2 text-sm font-bold <?= $change['type']==='up'?'bg-emerald-950/50 text-emerald-400':($change['type']==='down'?'bg-red-950/40 text-red-400':($change['type']==='first'?'bg-sky-950/40 text-sky-400':'bg-zinc-950 text-zinc-400')) ?>"><?= $change['type']==='up'?'🟢':($change['type']==='down'?'🔴':'⚪') ?> <?= e($change['label']) ?></p></section>
  <section class="card border-orange-900/60"><p class="text-sm font-bold text-orange-400">🎯 CURRENT TARGET</p><div class="mt-3 flex flex-wrap gap-2"><?php if($target): ?><span class="badge bg-orange-950 text-orange-300"><?= (int)$target['set_count'] ?> × <?= (int)$target['repetitions_min'] ?>–<?= (int)$target['repetitions_max'] ?></span><span class="badge bg-zinc-950 text-zinc-300">Increment <?= e(format_number($target['weight_increment'])) ?> kg</span><?php else: ?><span class="text-zinc-500">No programmed target</span><?php endif; ?></div><h2 class="mt-4 text-xl font-black"><?= e($progress['recommendation']['title']) ?></h2><p class="mt-2 leading-relaxed text-zinc-400"><?= e($progress['recommendation']['detail']) ?></p></section>
</div>

<section class="mb-5"><div class="mb-3"><p class="text-sm font-bold text-violet-400">📊 STATISTICS</p><h2 class="text-xl font-black">Useful numbers</h2></div><div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div class="card"><p class="text-xs text-zinc-500">Sessions</p><p class="metric"><?= (int)$stats['sessions'] ?></p></div><div class="card"><p class="text-xs text-zinc-500">Working sets</p><p class="metric"><?= (int)$stats['working_sets'] ?></p></div><div class="card"><p class="text-xs text-zinc-500">Average weight</p><p class="metric"><?= e(number_format((float)$stats['average_weight'],1)) ?> kg</p></div><div class="card"><p class="text-xs text-zinc-500">Best weight</p><p class="metric"><?= e(number_format((float)$stats['best_weight'],1)) ?> kg</p></div><div class="card"><p class="text-xs text-zinc-500">Best repetitions</p><p class="metric"><?= (int)$stats['best_repetitions'] ?></p></div><div class="card"><p class="text-xs text-zinc-500">Average repetitions</p><p class="metric"><?= e(number_format((float)$stats['average_repetitions'],1)) ?></p></div><div class="card"><p class="text-xs text-zinc-500">🏆 Personal records</p><p class="metric"><?= (int)$stats['personal_records'] ?></p></div><div class="card"><p class="text-xs text-zinc-500">🔥 Improvement streak</p><p class="metric"><?= $stats['sessions']>1?(int)$stats['current_streak']:'—' ?></p></div></div></section>

<section class="card mb-5"><div class="mb-4"><p class="text-sm font-bold text-violet-400">📈 PROGRESS</p><h2 class="text-xl font-black">Session-by-session evolution</h2></div><?php if(count($progress['chart'])<2): ?><div class="rounded-2xl bg-zinc-950 p-6 text-center"><h3 class="font-black">Only one workout recorded.</h3><p class="mt-2 text-sm text-zinc-500">Complete another session to unlock progression trends.</p></div><?php else: ?><div class="top-nav mb-5 flex gap-2 overflow-x-auto pb-2"><?php foreach(['best_weight'=>'Best weight','best_repetitions'=>'Best repetitions','best_set'=>'Best working set','average_weight'=>'Average weight'] as $metric=>$label): ?><button type="button" data-exercise-chart-tab="<?= e($metric) ?>" class="whitespace-nowrap rounded-full bg-zinc-800 px-4 py-2 text-sm font-semibold text-zinc-400"><?= e($label) ?></button><?php endforeach; ?></div><div class="h-72"><canvas id="exercise-progress-chart" data-exercise-chart='<?= e(json_encode($progress['chart'])) ?>'></canvas></div><?php endif; ?></section>

<section class="card mb-5"><div class="mb-4"><p class="text-sm font-bold text-sky-400">RECENT EVOLUTION</p><h2 class="text-xl font-black">What changed recently</h2></div><div class="space-y-0"><?php foreach($progress['timeline'] as $event): ?><div class="relative flex gap-4 pb-5 last:pb-0"><span class="absolute left-[15px] top-8 h-full w-px bg-zinc-800 last:hidden"></span><span class="relative flex h-8 w-8 shrink-0 items-center justify-center rounded-full <?= $event['type']==='record'?'bg-amber-950 text-amber-400':($event['type']==='improved'?'bg-emerald-950 text-emerald-400':($event['type']==='regressed'?'bg-red-950 text-red-400':'bg-zinc-800 text-zinc-400')) ?>"><?= $event['type']==='record'?'🏆':($event['type']==='improved'?'↑':($event['type']==='regressed'?'↓':'•')) ?></span><div><p class="font-bold"><?= e($event['label']) ?></p><p class="text-sm text-zinc-400"><?= e($setText($event['set'])) ?> · <?= e(date('M j, Y',strtotime($event['date']))) ?></p></div></div><?php endforeach; ?></div></section>

<section class="mb-5"><div class="mb-3"><p class="text-sm font-bold text-emerald-400">📅 WORKOUT HISTORY</p><h2 class="text-xl font-black">Recorded sessions</h2></div><div class="space-y-3"><?php foreach($progress['history'] as $session): ?><article class="card relative transition hover:-translate-y-0.5 hover:border-zinc-700"><a class="absolute inset-0 rounded-2xl" href="<?= e(route('workouts.show',['id'=>$session['id']])) ?>" aria-label="View workout"></a><div class="relative pointer-events-none flex items-start justify-between gap-3"><div><h3 class="font-black"><?= e(date('M j, Y',strtotime($session['performed_at']))) ?></h3><p class="text-sm text-zinc-500"><?= e($session['session_type']) ?><?php if($session['body_weight_kg']): ?> · ⚖️ <?= e(number_format((float)$session['body_weight_kg'],1)) ?> kg<?php endif; ?></p></div><?php if($session['is_pr']): ?><span class="badge bg-amber-950 text-amber-300">🏆 PR</span><?php endif; ?></div><div class="relative pointer-events-none mt-4 grid gap-3 sm:grid-cols-[auto_1fr]"><div class="rounded-xl bg-emerald-950/30 p-3"><p class="text-xs text-emerald-500">BEST SET</p><strong><?= e($historySetText($session['best'])) ?></strong></div><div class="space-y-2"><?php foreach(['warmup'=>'Warm-up','ramp'=>'Ramp-up','working'=>'Working sets'] as $kind=>$label):if(!$session[$kind])continue; ?><div class="flex flex-wrap items-center gap-2"><span class="w-24 text-xs text-zinc-500"><?= e($label) ?></span><?php foreach($session[$kind] as $set): ?><span class="rounded-lg bg-zinc-950 px-2 py-1 text-sm <?= $kind==='working'?'text-zinc-200':'text-zinc-500' ?>"><?= e($historySetText($set)) ?></span><?php endforeach; ?></div><?php endforeach; ?></div></div><p class="relative pointer-events-none mt-4 text-right text-sm font-bold text-emerald-400">View workout →</p></article><?php endforeach; ?></div><?php if($progress['hasMore']): ?><a href="<?= e(route('exercises.show',['id'=>$exercise['id']]).'?limit='.min(50,$limit+10)) ?>" class="btn-secondary mt-4 w-full">Load more sessions</a><?php endif; ?></section>

<section class="card mb-5"><div class="mb-4"><p class="text-sm font-bold text-amber-400">🏅 EXERCISE ACHIEVEMENTS</p><h2 class="text-xl font-black"><?= e($exercise['name']) ?> milestones</h2></div><?php if(!$progress['achievements']): ?><p class="text-zinc-500">Exercise-specific milestones will appear here as the program grows.</p><?php else: ?><div class="grid gap-3 sm:grid-cols-2"><?php foreach($progress['achievements'] as $achievement):$unlocked=(bool)$achievement['unlocked_at']; ?><div class="rounded-2xl border <?= $unlocked?'border-emerald-800 bg-emerald-950/25':'border-zinc-800 bg-zinc-950/50' ?> p-4"><div class="flex gap-3"><span class="text-2xl"><?= $unlocked?'✅':'🔒' ?></span><div><h3 class="font-black"><?= e($achievement['name']) ?></h3><p class="text-sm text-zinc-500"><?= e($achievement['description']) ?></p></div></div><?php if($unlocked): ?><p class="mt-3 text-xs text-emerald-400">Unlocked <?= e(date('M j, Y',strtotime($achievement['unlocked_at']))) ?></p><?php else: ?><div class="mt-3 h-2 overflow-hidden rounded-full bg-zinc-800"><div class="h-full rounded-full bg-emerald-600" style="width:<?= (int)$achievement['progress_percent'] ?>%"></div></div><p class="mt-1 text-right text-xs text-zinc-500"><?= (int)$achievement['progress_percent'] ?>%</p><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></section>

<section class="card border-sky-900/50"><p class="text-sm font-bold text-sky-400">💡 INSIGHTS</p><div class="mt-3 space-y-2"><?php foreach($progress['insights'] as $insight): ?><p class="flex gap-2 text-zinc-300"><span class="text-sky-400">•</span><?= e($insight) ?></p><?php endforeach; ?></div></section>
<?php endif; ?>
<script defer src="<?= e(asset('assets/js/exercise-progress.js')) ?>"></script>
