<?php
declare(strict_types=1);

use App\Core\Database;
use Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';
Dotenv::createImmutable(dirname(__DIR__))->safeLoad();

$root=dirname(__DIR__);$options=getopt('',['dry-run','selected-only','update-existing','with-media','metadata-only','dataset-path:']);
$dryRun=array_key_exists('dry-run',$options);$selectedOnly=array_key_exists('selected-only',$options);$updateExisting=array_key_exists('update-existing',$options);$withMedia=array_key_exists('with-media',$options);
if(!$selectedOnly){fwrite(STDERR,"Refusing an unbounded import. Use --selected-only.\n");exit(2);}
if($withMedia&&array_key_exists('metadata-only',$options)){fwrite(STDERR,"Choose --with-media or --metadata-only, not both.\n");exit(2);}
$datasetRoot=rtrim((string)($options['dataset-path']??($_ENV['EXERCISES_DATASET_PATH']??$root.'/storage/import-source/exercises-dataset')),'/\\');$jsonPath=$datasetRoot.'/data/exercises.json';
if(!is_file($jsonPath)){fwrite(STDERR,"Dataset not found: {$jsonPath}\nUse --dataset-path=/path/to/exercises-dataset.\n");exit(2);}
$config=require $root.'/config/exercise_dataset.php';$selected=[];$groupById=[];foreach($config['groups'] as $group=>$ids)foreach($ids as $id){$selected[]=$id;$groupById[$id]=$group;}
$records=json_decode((string)file_get_contents($jsonPath),true,512,JSON_THROW_ON_ERROR);$dataset=[];foreach($records as $record)$dataset[(string)$record['id']]=$record;
$report=['mode'=>$dryRun?'dry-run':'import','started_at'=>date(DATE_ATOM),'source'=>$config['source'],'dataset_commit'=>'unknown','selection_count'=>count($selected),'imported'=>[],'enriched'=>[],'ignored'=>[],'matches'=>[],'potential_duplicates'=>[],'media'=>[],'errors'=>[]];
$commitFile=$datasetRoot.'/.dataset-commit';if(is_file($commitFile))$report['dataset_commit']=trim((string)file_get_contents($commitFile));elseif(is_file($datasetRoot.'/.git/HEAD')){$head=trim((string)file_get_contents($datasetRoot.'/.git/HEAD'));if(str_starts_with($head,'ref: ')){$ref=$datasetRoot.'/.git/'.substr($head,5);if(is_file($ref))$head=trim((string)file_get_contents($ref));}$report['dataset_commit']=$head;}
$db=Database::connection();$groups=$db->query('SELECT name,id FROM muscle_groups')->fetchAll(PDO::FETCH_KEY_PAIR);$equipment=$db->query('SELECT name,id FROM equipment')->fetchAll(PDO::FETCH_KEY_PAIR);$locals=$db->query('SELECT * FROM exercises')->fetchAll();
$normalize=static fn(string $value):string=>trim((string)preg_replace('/[^a-z0-9]+/',' ',strtolower(iconv('UTF-8','ASCII//TRANSLIT',$value)?:$value)));
$byName=[];$byExternal=[];foreach($locals as $local){$byName[$normalize($local['name'])][]=$local;if($local['external_dataset_id'])$byExternal[$local['external_dataset_id']]=$local;}
$findLocal=static function(string $id,string $name)use(&$byExternal,&$byName,$normalize,$config):array{$explicit=$config['existing_matches'][$id]??null;if(isset($byExternal[$id]))return [$byExternal[$id],'external_dataset_id'];if($explicit&&isset($byName[$normalize($explicit)]))return [$byName[$normalize($explicit)][0],'explicit mapping'];$matches=$byName[$normalize($name)]??[];return [$matches[0]??null,$matches?'normalized name':null];};
$mediaRoot=$root.'/public/media/exercises';if(!$dryRun&&$withMedia){@mkdir($mediaRoot.'/images',0775,true);@mkdir($mediaRoot.'/gifs',0775,true);}
$update=$db->prepare('UPDATE exercises SET external_dataset_id=?,canonical_name=?,dataset_category=?,body_part=?,dataset_equipment=?,target_muscle=?,dataset_muscle_group=?,secondary_muscles=?,instructions=?,instruction_steps=?,image_path=?,gif_path=?,media_attribution=?,source=?,imported_at=NOW() WHERE id=?');
$insert=$db->prepare('INSERT INTO exercises(muscle_group_id,equipment_id,name,recommended_rest_seconds,weight_increment,load_semantics,external_dataset_id,canonical_name,dataset_category,body_part,dataset_equipment,target_muscle,dataset_muscle_group,secondary_muscles,instructions,instruction_steps,image_path,gif_path,media_attribution,source,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())');
if(!$dryRun)$db->beginTransaction();
try{
foreach($selected as $id){
    if(!isset($dataset[$id])){$report['errors'][]="Selected dataset id {$id} is missing.";continue;}$item=$dataset[$id];$preferred=$config['preferred_names'][$id]??ucwords((string)$item['name']);[$local,$matchType]=$findLocal($id,$preferred);$group=$groupById[$id];
    if(!isset($groups[$group])){$report['errors'][]="Missing local muscle group {$group}.";continue;}$equipmentName=$config['equipment_map'][strtolower((string)$item['equipment'])]??null;$equipmentId=$equipmentName&&isset($equipment[$equipmentName])?(int)$equipment[$equipmentName]:null;
    $imagePath=$local['image_path']??null;$gifPath=$local['gif_path']??null;foreach([['image','images','imagePath'],['gif_url','gifs','gifPath']] as [$field,$folder,$pathVar]){if(empty($item[$field]))continue;$source=$datasetRoot.'/'.str_replace(['/', '\\'],DIRECTORY_SEPARATOR,(string)$item[$field]);$destination=$mediaRoot.'/'.$folder.'/'.basename((string)$item[$field]);$report['media'][]=['exercise_id'=>$id,'type'=>$field,'source'=>$item[$field],'destination'=>str_replace($root.'/public','',$destination),'action'=>$withMedia?($dryRun?'would copy':(is_file($destination)?'reused':'copied')):'metadata only'];if($withMedia){if(!is_file($source))throw new RuntimeException("Missing media {$source}");if(!$dryRun&&!is_file($destination)&&!copy($source,$destination))throw new RuntimeException("Unable to copy {$source}");$$pathVar='/media/exercises/'.$folder.'/'.basename((string)$item[$field]);}}
    $values=[$id,(string)$item['name'],$item['category']??null,$item['body_part']??null,$item['equipment']??null,$item['target']??null,$item['muscle_group']??null,json_encode($item['secondary_muscles']??[],JSON_UNESCAPED_UNICODE),$item['instructions']['en']??null,json_encode($item['instruction_steps']['en']??[],JSON_UNESCAPED_UNICODE),$imagePath,$gifPath,$item['attribution']??null,$config['source']];
    if($local){$report['matches'][]=['dataset_id'=>$id,'dataset_name'=>$item['name'],'local_id'=>(int)$local['id'],'local_name'=>$local['name'],'method'=>$matchType];if(!$updateExisting&&!isset($byExternal[$id])){$report['ignored'][]=['dataset_id'=>$id,'reason'=>'existing exercise; use --update-existing'];continue;}$report['enriched'][]=['dataset_id'=>$id,'local_id'=>(int)$local['id'],'name'=>$local['name']];if(!$dryRun)$update->execute([...$values,(int)$local['id']]);continue;}
    $normalizedMatches=$byName[$normalize($preferred)]??[];if(count($normalizedMatches)>1){$report['potential_duplicates'][]=['dataset_id'=>$id,'name'=>$preferred,'local_ids'=>array_column($normalizedMatches,'id')];$report['ignored'][]=['dataset_id'=>$id,'reason'=>'ambiguous normalized name'];continue;}
    $report['imported'][]=['dataset_id'=>$id,'name'=>$preferred,'group'=>$group,'equipment'=>$equipmentName];if(!$dryRun){$loadSemantics=strtolower((string)$item['equipment'])==='dumbbell'?'per_dumbbell':(in_array(strtolower((string)$item['equipment']),['cable','leverage machine','sled machine'],true)?'machine_stack':'total');$increment=$loadSemantics==='machine_stack'?5:($loadSemantics==='per_dumbbell'?2:2.5);$insert->execute([(int)$groups[$group],$equipmentId,$preferred,90,$increment,$loadSemantics,...$values]);$newId=(int)$db->lastInsertId();$new=['id'=>$newId,'name'=>$preferred,'external_dataset_id'=>$id,'image_path'=>$imagePath,'gif_path'=>$gifPath];$byName[$normalize($preferred)][]=$new;$byExternal[$id]=$new;}
}
if($report['errors'])throw new RuntimeException('Import validation failed.');if(!$dryRun)$db->commit();
}catch(Throwable $e){if(!$dryRun&&$db->inTransaction())$db->rollBack();$report['errors'][]=$e->getMessage();}
$report['finished_at']=date(DATE_ATOM);$report['summary']=['imported'=>count($report['imported']),'enriched'=>count($report['enriched']),'ignored'=>count($report['ignored']),'matches'=>count($report['matches']),'potential_duplicates'=>count($report['potential_duplicates']),'media'=>count($report['media']),'errors'=>count($report['errors'])];$reportDir=$root.'/storage/import-reports';@mkdir($reportDir,0775,true);$reportPath=$reportDir.'/exercise-import-'.date('Ymd-His').'-'.($dryRun?'dry-run':'import').'.json';file_put_contents($reportPath,json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));
echo strtoupper($report['mode'])." — selected {$report['selection_count']}\n";foreach($report['summary'] as $label=>$count)echo str_pad($label,22).$count."\n";echo "Report: {$reportPath}\n";exit($report['errors']?1:0);
