<?php $title='Settings'; ?>
<div class="mb-6"><p class="text-sm font-semibold text-emerald-400">PERSONALIZE YOUR EXPERIENCE</p><h1 class="mt-1 text-3xl font-black">Settings</h1><p class="mt-2 text-zinc-400">Make Home Gym work the way you train.</p></div>
<form method="post" action="<?= e(route('settings.store')) ?>" class="grid max-w-3xl gap-4"><?= csrf_field() ?>
  <section class="card"><div class="mb-4 flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-950 text-xl">🎨</span><div><h2 class="font-black">Appearance</h2><p class="text-sm text-zinc-500">Choose the atmosphere that feels best.</p></div></div><label for="appearance-theme">Color theme</label><select id="appearance-theme" name="appearance_theme" data-theme-select><option value="dark" <?= ($settings['appearance_theme']??'dark')==='dark'?'selected':'' ?>>Dark mode</option><option value="light" <?= ($settings['appearance_theme']??'dark')==='light'?'selected':'' ?>>Light mode</option></select></section>
  <section class="card"><div class="mb-4 flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-950 text-xl">📏</span><div><h2 class="font-black">Monthly check-up</h2><p class="text-sm text-zinc-500">A gentle reminder on the first day of each month.</p></div></div><label class="flex items-center gap-3"><input class="h-5 w-5" type="checkbox" name="measurement_reminder_enabled" value="1" <?= ($settings['measurement_reminder_enabled']??'1')==='1'?'checked':'' ?>><span>Show the monthly measurement reminder</span></label></section>
  <section class="card"><div class="mb-4 flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-sky-950 text-xl">⏱️</span><div><h2 class="font-black">Rest timer</h2><p class="text-sm text-zinc-500">Control how the app gets your attention.</p></div></div><label class="mb-3 flex items-center gap-3"><input class="h-5 w-5" type="checkbox" name="timer_sound_enabled" value="1" <?= ($settings['timer_sound_enabled']??'1')==='1'?'checked':'' ?>><span>Play a short sound when rest ends</span></label><label class="flex items-center gap-3"><input class="h-5 w-5" type="checkbox" name="timer_vibration_enabled" value="1" <?= ($settings['timer_vibration_enabled']??'1')==='1'?'checked':'' ?>><span>Vibrate when supported</span></label></section>
  <section class="card"><div class="mb-4 flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-950 text-xl">⚖️</span><div><h2 class="font-black">Body-weight trend</h2><p class="text-sm text-zinc-500">This only changes how weight trends are interpreted.</p></div></div><label for="weight-goal">Current goal</label><select id="weight-goal" name="body_weight_goal_direction"><option value="unset">No goal — neutral trends</option><option value="gain" <?= ($settings['body_weight_goal_direction']??'unset')==='gain'?'selected':'' ?>>Gain weight</option><option value="lose" <?= ($settings['body_weight_goal_direction']??'unset')==='lose'?'selected':'' ?>>Lose weight</option><option value="maintain" <?= ($settings['body_weight_goal_direction']??'unset')==='maintain'?'selected':'' ?>>Maintain weight</option></select></section>
  <button class="btn-primary w-full sm:w-auto sm:justify-self-end">Save settings</button>
</form>
